-- MVP Database Schema for GradPath

-- Universities table
CREATE TABLE IF NOT EXISTS universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT NOT NULL,
    city TEXT NOT NULL,
    website TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Specialties table
CREATE TABLE IF NOT EXISTS specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id BIGINT REFERENCES universities(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    description TEXT,
    faculty_name TEXT,
    degree_type TEXT DEFAULT 'full-time',
    duration_years NUMERIC(2,1),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Admission statistics table
CREATE TABLE IF NOT EXISTS admission_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialty_id BIGINT REFERENCES specialties(id) ON DELETE CASCADE,
    year INT NOT NULL,
    budget_places INT DEFAULT 0,
    paid_places INT DEFAULT 0,
    passing_score_budget NUMERIC(5,1),
    passing_score_paid NUMERIC(5,1),
    total_applications INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE universities ENABLE ROW LEVEL SECURITY;
ALTER TABLE specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE admission_stats ENABLE ROW LEVEL SECURITY;

-- Public read access policies
CREATE POLICY "Public read universities" ON universities FOR SELECT USING (true);
CREATE POLICY "Public read specialties" ON specialties FOR SELECT USING (true);
CREATE POLICY "Public read admission_stats" ON admission_stats FOR SELECT USING (true);

-- Admin write access (adjust for your needs)
CREATE POLICY "Admin write universities" ON universities FOR ALL USING (true);
CREATE POLICY "Admin write specialties" ON specialties FOR ALL USING (true);
CREATE POLICY "Admin write admission_stats" ON admission_stats FOR ALL USING (true);