import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

export type Language = 'ru' | 'en' | 'be';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'gradpath-language';

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Profile
    'profile.title': 'Профиль',
    'profile.back': 'Назад',
    'profile.email': 'Email',
    'profile.role': 'Роль',
    'profile.admin': 'Администратор',
    'profile.user': 'Пользователь',
    'profile.appearance': 'Внешний вид',
    'profile.appearanceDesc': 'Выберите тему оформления',
    'profile.theme.light': 'Светлая',
    'profile.theme.dark': 'Тёмная',
    'profile.theme.highContrast': 'Для слабовидящих',
    'profile.language': 'Язык интерфейса',
    'profile.languageDesc': 'Выберите язык интерфейса',
    'profile.actions': 'Действия',
    'profile.adminPanel': 'Перейти в админ-панель',
    'profile.changePassword': 'Изменить пароль',
    'profile.logout': 'Выйти из аккаунта',
    'profile.logoutSuccess': 'Выход выполнен',
    'profile.logoutSuccessDesc': 'Вы успешно вышли из аккаунта.',
    'profile.loading': 'Загрузка...',
    'profile.university': 'Университет',
    'profile.universityDesc': 'Ваш университет и специальность',
    'profile.faculty': 'Факультет',
    'profile.specialty': 'Специальность',
    'profile.course': 'Курс',
    'profile.graduationYear': 'Год выпуска',
    'profile.verification': 'Верификация',
    'profile.verified': 'Верифицирован',
    'profile.notVerified': 'Не верифицирован',
    'profile.editUniversity': 'Редактировать',
    'profile.fillUniversity': 'Заполнить профиль',
    'profile.noUniversity': 'Университет не указан. Заполните профиль, чтобы получать персональные рекомендации.',
    'profile.digitalProfile': 'Цифровой профиль',
    'profile.digitalProfileDesc': 'Навыки, языки, проекты и сертификаты',
    'profile.skills': 'Навыки',
    'profile.languages': 'Языки',
    'profile.projects': 'Проекты',
    'profile.certificates': 'Сертификаты',
    'profile.addSkill': 'Добавить навык',
    'profile.addLanguage': 'Добавить язык',
    'profile.addProject': 'Добавить проект',
    'profile.addCertificate': 'Добавить сертификат',
    'profile.editSkill': 'Редактировать навык',
    'profile.editLanguage': 'Редактировать язык',
    'profile.editProject': 'Редактировать проект',
    'profile.editCertificate': 'Редактировать сертификат',
    'profile.skillName': 'Название',
    'profile.proficiencyLevel': 'Уровень владения',
    'profile.languageName': 'Язык',
    'profile.cefrLevel': 'Уровень (CEFR)',
    'profile.projectTitle': 'Название *',
    'profile.projectRole': 'Роль',
    'profile.projectDescription': 'Описание',
    'profile.projectUrl': 'Ссылка',
    'profile.projectStartDate': 'Дата начала',
    'profile.projectEndDate': 'Дата окончания',
    'profile.certName': 'Название *',
    'profile.certIssuer': 'Организация *',
    'profile.certUrl': 'Ссылка',
    'profile.certIssueDate': 'Дата выдачи',
    'profile.certExpiryDate': 'Срок действия',
    'profile.skillsEmpty': 'Навыки не добавлены. Добавьте хотя бы 3-5 навыков для улучшения профиля.',
    'profile.languagesEmpty': 'Языки не добавлены.',
    'profile.projectsEmpty': 'Проекты не добавлены.',
    'profile.certificatesEmpty': 'Сертификаты не добавлены.',
    'profile.skillAdded': 'Навык добавлен',
    'profile.skillUpdated': 'Навык обновлён',
    'profile.skillDeleted': 'Навык удалён',
    'profile.languageAdded': 'Язык добавлен',
    'profile.languageUpdated': 'Язык обновлён',
    'profile.languageDeleted': 'Язык удалён',
    'profile.projectAdded': 'Проект добавлен',
    'profile.projectUpdated': 'Проект обновлён',
    'profile.projectDeleted': 'Проект удалён',
    'profile.certAdded': 'Сертификат добавлен',
    'profile.certUpdated': 'Сертификат обновлён',
    'profile.certDeleted': 'Сертификат удалён',
    'survey.title': 'Карьерная траектория',
    'survey.stillStudying': 'Опрос выпускников будет доступен после окончания университета.',
    'survey.available': 'Доступен опрос ({months} мес. после выпуска)',
    'survey.button': 'Пройти опрос',
    'survey.employed': 'Работаете ли вы сейчас?',
    'survey.country': 'Страна',
    'survey.company': 'Компания',
    'survey.position': 'Должность',
    'survey.salary': 'Зарплата (в USD)',
    'survey.inSpecialty': 'Работаете по специальности?',
    'survey.submit': 'Отправить',
    'survey.thanks': 'Спасибо!',
    'survey.saved': 'Ваш ответ сохранён',
    'survey.yourPath': 'Ваш путь:',
    'survey.allDone': 'Все доступные опросы пройдены.',
    'survey.nextMilestone': 'Следующий: {milestone}',
    'survey.wait': 'Опрос пока недоступен. Возвращайтесь после выпуска.',
    'survey.noData': 'Нет данных для отображения.',
    'survey.milestone.6months': 'Через 6 месяцев после выпуска',
    'survey.milestone.12months': 'Через 12 месяцев после выпуска',
    'survey.milestone.2years': 'Через 2 года после выпуска',
    'survey.milestone.4years': 'Через 4 года после выпуска',
    'survey.yes': 'Да',
    'survey.no': 'Нет',
    'survey.cancel': 'Отмена',
    'survey.sending': 'Отправка...',
    'survey.employedError': 'Ошибка',
    'survey.employedErrorDesc': 'Ответьте на вопрос о трудоустройстве',
    'survey.error': 'Ошибка',
    'survey.dialogTitle': 'Опрос выпускника',
    'survey.notEmployed': 'Не работает',
    'survey.shortMonths': 'мес',
    'survey.shortYears': 'года',
    // Survey Landing
    'surveyLanding.badge': 'Опрос выпускников',
    'surveyLanding.title': 'Опрос по окончании курса',
    'surveyLanding.subtitle': 'Ваш опыт обучения и трудоустройства важен. Пройдите опрос, чтобы помочь будущим студентам сделать правильный выбор.',
    'surveyLanding.ctaProfile': 'Пройти опрос',
    'surveyLanding.ctaRegister': 'Зарегистрироваться',
    'surveyLanding.ctaQuiz': 'Пройти тест на профориентацию',
    'surveyLanding.howItWorksTitle': 'Как это работает',
    'surveyLanding.howItWorksDesc': 'Мы связываемся с вами через определённое время после выпуска, чтобы узнать, как складывается ваша карьера.',
    'surveyLanding.milestone0desc': 'Первые впечатления о работе и поиске первых позиций',
    'surveyLanding.milestone1desc': 'Адаптация на работе, первые карьерные решения',
    'surveyLanding.milestone2desc': 'Карьерный рост, смена компаний, расширение навыков',
    'surveyLanding.milestone3desc': 'Устойчивая карьера, лидерские позиции, сравнение с ожиданиями',
    'surveyLanding.whyTitle': 'Почему это важно',
    'surveyLanding.whyDesc': 'Ваши ответы помогают абитуриентам и студентам принимать обоснованные решения.',
    'surveyLanding.benefit1Title': 'Для будущих студентов',
    'surveyLanding.benefit1Desc': 'Абитуриенты увидят реальные данные о трудоустройстве и зарплатах по каждой специальности.',
    'surveyLanding.benefit2Title': 'Для университетов',
    'surveyLanding.benefit2Desc': 'Вузы получат обратную связь и смогут улучшить образовательные программы.',
    'surveyLanding.benefit3Title': 'Для рынка труда',
    'surveyLanding.benefit3Desc': 'Работодатели увидят, какие навыки и компетенции востребованы.',
    'surveyLanding.statsTitle': 'Станьте частью данных, которые меняют образование',
    'surveyLanding.statsDesc': 'Каждый ваш ответ помогает создать более точную картину рынка труда и образования в Беларуси.',
    'surveyLanding.statsCta': 'Пройти опрос',
    'surveyLanding.stat1Label': 'Этапов опроса',
    'surveyLanding.stat2Label': 'Конфиденциальность',
    'surveyLanding.stat3Label': 'Языка',
    'surveyLanding.stat4Label': 'Время для заполнения',
    'surveyLanding.faqTitle': 'Часто задаваемые вопросы',
    'surveyLanding.faq1q': 'Кто может пройти опрос?',
    'surveyLanding.faq1a': 'Опрос доступен для всех выпускников белорусских университетов, прошедших не менее 6 месяцев с момента окончания обучения.',
    'surveyLanding.faq2q': 'Как часто будут приходить опросы?',
    'surveyLanding.faq2a': 'Опросы приходят 4 раза: через 6 месяцев, 12 месяцев, 2 года и 4 года после выпуска. Это позволяет отслеживать динамику вашей карьеры.',
    'surveyLanding.faq3q': 'Мои данные будут опубликованы?',
    'surveyLanding.faq3a': 'Нет. Все данные агрегируются и обезличиваются. Мы публикуем только общую статистику без персональной информации.',
    'surveyLanding.faq4q': 'Можно ли пропустить опрос?',
    'surveyLanding.faq4a': 'Да, вы можете не отвечать на опрос. Однако ваш вклад помогает создать более точную картину для будущих студентов.',
    'surveyLanding.finalTitle': 'Ваш опыт — ваш вклад в будущее образования',
    'surveyLanding.finalDesc': 'Пройдите опрос и помогите сделать образование в Беларуси более прозрачным и ориентированным на результат.',
    'surveyLanding.cvHint': 'Вы также можете использовать информацию из анкеты (иностранные языки, компьютерные навыки, образовательный бэкграунд) для создания резюме.',
    'surveyLanding.card1Title': 'Уже есть аккаунт?',
    'surveyLanding.card1Desc': 'Войдите в свой профиль и заполните анкету по окончании курса. Это займёт не более 10 минут.',
    'surveyLanding.loginCta': 'Войти и заполнить анкету',
    'surveyLanding.card2Title': 'Ещё не зарегистрированы?',
    'surveyLanding.card2Desc': 'Создайте профиль с информацией о вашей специальности, заполните анкету и разместите резюме в базе GradPath.',
    'surveyLanding.quizTitle': 'Профориентационный тест',
    'surveyLanding.quizDesc': 'Не уверены в выборе специальности? Пройдите наш тест, чтобы узнать, какие направления обучения вам подходят.',
    'surveyLanding.supportTitle': 'Остались вопросы?',
    'surveyLanding.supportDesc': 'Если у вас есть сомнения или вопросы об анкете, посетите раздел FAQ или свяжитесь с нами.',
    'surveyLanding.faqLink': 'Часто задаваемые вопросы',
    'surveyLanding.contactLink': 'Связаться с нами',
    'surveyLanding.sidebar.main': 'Для студентов и выпускников',
    'surveyLanding.sidebar.questionnaire': 'Анкета по окончании курса',
    'surveyLanding.sidebar.register': 'Зарегистрироваться',
    'surveyLanding.sidebar.quiz': 'Профориентационный тест',
    'surveyLanding.sidebar.internships': 'Стажировки',
    'surveyLanding.sidebar.events': 'Мероприятия',
    'surveyLanding.sidebar.faq': 'FAQ и поддержка',
    'surveyLanding.introBold': 'Вы завершаете обучение или заканчиваете магистратуру?',
    'surveyLanding.introText': 'Заполните анкету, если вы учитесь в одном из университетов-партнёров GradPath. Бакалавриат, магистратура, аспирантура — перед окончанием обучения у вас есть возможность высказать своё мнение о пройденном образовательном пути.',
    'surveyLanding.ctaSectionTitle': 'Заполните анкету:',
    'surveyLanding.doubtsTitle': 'Остались вопросы об анкете?',
    'surveyLanding.doubtsDesc': 'Мы создали раздел «FAQ и поддержка», чтобы помочь вам.',
    // Navigation
    'nav.home': 'Главная',
    'nav.analytics': 'Аналитика',
    // Hero
    'hero.title': 'Всё о высшем образовании',
    'hero.chooseUni': 'Выбрать ВУЗ',
    'hero.forApplicants': 'Для абитуриентов',
    'hero.analytics': 'Аналитика',
    'hero.register': 'Регистрация',
    'hero.search': 'Поиск университета или специальности...',
    'hero.noResults': 'Университеты не найдены',
    'hero.unis': 'ВУЗов',
    'hero.vacancies': 'Вакансий в базе',
    'hero.sources': 'Источников данных',
    'hero.dataNotice': 'Данные получены из открытых источников: rabota.by, сайты ВУЗов',
    // Footer
    'footer.statistics': 'Статистика',
    'footer.universities': 'ВУЗы',
    'footer.dataAnalytics': 'Данные и аналитика',
    'footer.about': 'О проекте',
    'footer.support': 'Поддержка',
    'footer.internships': 'Стажировки',
    'footer.events': 'Мероприятия',
    'footer.careerMap': 'Карта карьер',
    'footer.blog': 'Блог',
    'footer.team': 'Команда',
    'footer.contact': 'Контакты',
    'footer.faq': 'FAQ',
    'footer.aboutProject': 'О нас',
    'footer.admission': 'Поступление',
    'footer.analytics': 'Аналитика',
    'footer.helpCenter': 'Центр помощи',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'footer.allRightsReserved': 'Все права защищены.',
    'footer.services': 'Наши услуги',
    'footer.careerQuiz': 'Карьерный тест',
    'footer.surveyLanding': 'Опрос выпускников',
    'footer.professionSelection': 'Подбор профессии',
    'footer.students': 'Студентам',
    // Quick Links
    'quickLinks.forApplicants': 'Для абитуриентов',
    'quickLinks.forApplicantsDesc': 'Проходные баллы, специальности, сроки подачи документов',
    'quickLinks.forStudents': 'Для студентов',
    'quickLinks.forStudentsDesc': 'Рынок труда, зарплаты, требования к опыту',
    'quickLinks.statistics': 'Статистика',
    'quickLinks.statisticsDesc': 'Вакансии, зарплаты, ML-анализ рынка труда',
    'quickLinks.admission': 'Поступление',
    'quickLinks.admissionDesc': 'Баллы прошлых лет, статистика зачислений',
    // Universities Section
    'unis.title': 'Выбери свой университет.',
    'unis.subtitle': 'Информация о государственных университетах Беларуси. Указаны средние проходные баллы за 2025 год.',
    'unis.inCatalog': 'В каталоге',
    'unis.universities': 'университетов',
    'unis.totalInRB': 'Всего в РБ',
    'unis.institutions': 'учреждений ВО',
    'unis.avgScore': 'Средний балл',
    'unis.forAdmission': 'для поступления',
    'unis.sourceNote': 'Источники данных: Средние проходные баллы указаны за 2025 год. Данные предоставлены для справки.',
    // Applicants Page
    'applicants.title': 'Выбери своё будущее осознанно',
    'applicants.subtitle': 'Сравни университеты, специальности и узнай реальные перспективы трудоустройства.',
    'applicants.badge': 'Для абитуриентов',
    'applicants.unis': 'университетов',
    'applicants.unisDesc': 'Детальная информация о ведущих вузах Беларуси',
    'applicants.jobMarket': 'Рынок труда',
    'applicants.jobMarketDesc': 'Анализ вакансий и востребованности специальностей',
    'applicants.demand': 'Спрос на рынке',
    'applicants.demandDesc': 'Анализ востребованности специальностей',
    // Students Page
    'students.title': 'Подготовься к рынку труда',
    'students.subtitle': 'Узнай, какие навыки востребованы, сколько платят работодатели и как построить успешную карьеру.',
    'students.badge': 'Для студентов',
    'students.jobMarket': 'Рынок труда',
    'students.jobMarketDesc': 'Актуальная статистика вакансий и зарплат',
    'students.criteria': 'Важные критерии',
    'students.criteriaDesc': 'ML-анализ факторов успешного трудоустройства',
    'students.growth': 'Карьерный рост',
    'students.growthDesc': 'Пути развития в разных профессиях',
    // Market Section
    'market.title': 'Рынок труда',
    'market.titleValue': 'Знай свою ценность.',
    'market.vacancies': 'вакансий',
    'market.high': 'высокий',
    'market.medium': 'средний',
    'market.low': 'низкий',
    'market.up': 'растёт',
    'market.noExperience': 'Без опыта',
    'market.years': 'года',
    'market.analysis': 'Анализ {count} вакансий с rabota.by.',
    'market.updated': 'Обновлено',
    // Categories - from database
    'category.it': 'ИТ',
    'category.medicine': 'Медицина',
    'category.engineering': 'Инженерия',
    'category.economics': 'Экономика',
    'category.education': 'Педагогика',
    'category.law': 'Юриспруденция',
    // Professions Section
    'professions.title': 'Востребованные профессии',
    'professions.subtitle': 'Топ специальностей по количеству вакансий и уровню зарплат',
    'professions.all': 'Все',
    'professions.highDemand': 'Высокий спрос',
    'professions.mediumDemand': 'Средний спрос',
    'professions.lowDemand': 'Низкий спрос',
    'professions.workers': 'Рабочие',
    'professions.employees': 'Служащие',
    'professions.specialists': 'Специалисты',
    'professions.loadError': 'Не удалось загрузить данные о профессиях.',
    // Analysis Section
    'analysis.rocAuc': 'ROC-AUC',
    'analysis.accuracyVal': 'Точность (Accuracy)',
    'analysis.accuracyDesc': 'Доля правильных предсказаний',
    'analysis.precisionVal': 'Precision',
    'analysis.precisionDesc': 'Точность положительных предсказаний',
    'analysis.recallVal': 'Recall',
    'analysis.recallDesc': 'Полнота выявления',
    'stats.title': 'Данные о рынке труда',
    'stats.subtitle': 'Полная аналитика вакансий, зарплат и прогнозы на основе машинного обучения.',
    'stats.vacancies': 'Вакансии',
    'stats.salaries': 'Зарплаты',
    'stats.mlAnalysis': 'ML-анализ',
    'stats.methodology': 'Методология',
    'stats.vacanciesAnalytics': 'Аналитика рынка труда',
    'stats.vacanciesAnalyticsDesc': 'Данные с rabota.by',
    'stats.totalVacancies': 'Всего вакансий',
    'stats.byCategories': 'по {count} категориям',
    'stats.topDirection': 'Топ направление',
    'stats.noData': 'Нет данных',
    'stats.vacanciesCount': 'вакансий',
    'stats.avgSalary': 'Средняя зарплата',
    'stats.categories': 'Категорий',
    'stats.directions': 'направлений',
    'stats.detailedStats': 'Детальная статистика по направлениям',
    'stats.category': 'Категория',
    'stats.vacanciesShort': 'Вакансий',
    'stats.avgSalaryShort': 'Ср. зарплата',
    'stats.range': 'Диапазон',
    'stats.allVacancies': 'Все вакансии',
    'stats.vacancy': 'Вакансия',
    'stats.company': 'Компания',
    'stats.city': 'Город',
    'stats.salary': 'Зарплата',
    'stats.source': 'Источник',
    // Salary Statistics
    // Auth
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.year': 'Год',
    'common.noData': 'Н/Д',
    // University Detail
    'uni.notFound': 'Университет не найден',
    'uni.notFoundDesc': 'К сожалению, информация о данном университете отсутствует.',
    'uni.backToList': 'Вернуться к списку',
    'uni.about': 'О университете',
    'uni.website': 'Сайт',
    'uni.scores': 'Баллы',
    'uni.faculties': 'факультетов',
    'uni.specialties': 'специальностей',
    // Chat
    // Admission Page
    'admission.title': 'Статистика поступления',
    'admission.subtitle': 'Исторические данные о проходных баллах и количестве мест',
    'admission.allYears': 'Все годы',
    'admission.allUniversities': 'Все университеты',
    'admission.allFaculties': 'Все факультеты',
    'admission.university': 'Университет',
    'admission.faculty': 'Факультет',
    'admission.activeFilters': 'Активные фильтры',
    'admission.budgetPlaces': 'Бюджетных мест',
    'admission.paidPlaces': 'Платных мест',
    'admission.avgScore': 'Средний балл',
    'admission.competition': 'Конкурс (чел/место)',
    'admission.table': 'Таблица',
    'admission.charts': 'Графики',
    'admission.comparison': 'Сравнение по годам',
    'admission.detailStats': 'Детальная статистика по специальностям',
    'admission.detailStatsDesc': 'Данные о проходных баллах и количестве мест',
    'admission.specialty': 'Специальность',
    'admission.uni': 'Университет',
    'admission.year': 'Год',
    'admission.budget': 'Бюджет',
    'admission.paid': 'Платное',
    'admission.minScore': 'Мин. балл',
    'admission.avgScoreShort': 'Ср. балл',
    'admission.applications': 'Заявок',
    'admission.noData': 'Нет данных для отображения.',
    'admission.noDataDesc': 'Данные загружаются из базы. Убедитесь, что таблица admission_stats заполнена.',
    'admission.placesDynamics': 'Динамика количества мест',
    'admission.placesDynamicsDesc': 'Бюджетные и платные места по годам',
    'admission.scoreDynamics': 'Динамика проходных баллов',
    'admission.scoreDynamicsDesc': 'Средний проходной балл по годам',
    'admission.minScores': 'Минимальные проходные баллы',
    'admission.minScoresDesc': 'Динамика минимальных баллов по годам',
    'admission.noChartData': 'Нет данных для графика',
    'admission.comparisonTitle': 'Сравнение проходных баллов по годам',
    'admission.comparisonDesc': 'Выберите специальность для детального сравнения показателей за разные годы',
    'admission.comparisonNeedData': 'Для сравнения нужны данные за несколько лет',
    'admission.selectAllYears': 'Выберите "Все годы" в фильтре для просмотра сравнения',
    'admission.budgetShort': 'Бюджет',
    'admission.applicationsShort': 'Заявки',
    'admission.dataSource': 'Источник данных:',
    'admission.dataSourceDesc': 'Статистика загружается из базы данных. Для обновления данных используйте парсинг в панели администратора или добавьте данные вручную. Отображаются только реальные данные из таблицы admission_stats.',
    'admission.yearBadge': 'год',
    // Internships
    'internships.title': 'Стажировки для студентов',
    'internships.subtitle': 'Актуальные стажировки и вакансии для студентов и выпускников в Беларуси. Начните свою карьеру уже во время учебы.',
    'internships.searchPlaceholder': 'Поиск по названию или компании...',
    'internships.filterDirection': 'Направление',
    'internships.filterCity': 'Город',
    'internships.filterType': 'Тип',
    'internships.allDirections': 'Все направления',
    'internships.allCities': 'Все города',
    'internships.allTypes': 'Все типы',
    'internships.typePaid': 'Платные',
    'internships.typeUnpaid': 'Без оплаты',
    'internships.typeUnknown': 'Уточняется',
    'internships.badgePaid': 'Платно',
    'internships.badgeUnpaid': 'Без оплаты',
    'internships.badgeUnknown': 'Уточняется',
    'internships.statsTotal': 'Всего стажировок',
    'internships.statsPaid': 'Платно',
    'internships.statsIt': 'IT стажировки',
    'internships.statsCompanies': 'Компаний',
    'internships.salaryNotSpecified': 'Не указана',
    'internships.salaryFrom': 'от {value}',
    'internships.salaryTo': 'до {value}',
    'internships.today': 'Сегодня',
    'internships.yesterday': 'Вчера',
    'internships.daysAgo': '{days} дня назад',
    'internships.apply': 'Откликнуться',
    'internships.soon': 'Скоро',
    'internships.empty': 'По вашему запросу ничего не найдено',
    'internships.resetFilters': 'Сбросить фильтры',
    'internships.loadError': 'Не удалось загрузить стажировки',
    'internships.retry': 'Повторить',
    // Events
    'events.title': 'Карьерные мероприятия',
    'events.subtitle': 'Ярмарки вакансий, дни открытых дверей, митапы и воркшопы для студентов и выпускников.',
    'events.searchPlaceholder': 'Поиск по названию или организатору...',
    'events.filterType': 'Тип',
    'events.filterCity': 'Город',
    'events.filterFormat': 'Формат',
    'events.allTypes': 'Все типы',
    'events.allCities': 'Все города',
    'events.allFormats': 'Все форматы',
    'events.statsTotal': 'Всего мероприятий',
    'events.statsUpcoming': 'Предстоящих',
    'events.statsOrganizers': 'Организаторов',
    'events.statsCities': 'Городов',
    'events.tabUpcoming': 'Предстоящие',
    'events.tabAll': 'Все',
    'events.formatOffline': 'Офлайн',
    'events.formatOnline': 'Онлайн',
    'events.formatHybrid': 'Гибрид',
    'events.typeCareerFair': 'Ярмарка вакансий',
    'events.typeOpenDay': 'День открытых дверей',
    'events.typeMeetup': 'Митап',
    'events.typeWorkshop': 'Воркшоп',
    'events.typeLecture': 'Лекция',
    'events.typeOther': 'Другое',
    'events.orgCompany': 'Компания',
    'events.orgUniversity': 'ВУЗ',
    'events.orgStudentOrg': 'Студ. организация',
    'events.orgOther': 'Другое',
    'events.register': 'Записаться',
    'events.soon': 'Скоро',
    'events.empty': 'По вашему запросу ничего не найдено',
    'events.resetFilters': 'Сбросить фильтры',
    'events.loadError': 'Не удалось загрузить мероприятия',
    'events.retry': 'Повторить',
    // Blog
    'blog.title': 'Блог',
    'blog.subtitle': 'Статьи о карьере, образовании, поступлении и рынке труда в Беларуси. Аналитика и советы от GradPath.',
    'blog.searchPlaceholder': 'Поиск по статьям...',
    'blog.allTags': 'Все',
    'blog.readMore': 'Читать дальше',
    'blog.empty': 'По вашему запросу ничего не найдено',
    'blog.resetFilters': 'Сбросить фильтры',
    'blog.loadError': 'Не удалось загрузить статьи',
    'blog.retry': 'Повторить',
    'blog.backToList': 'Назад к блогу',
    'blog.notFound': 'Статья не найдена',
    // Specialty Analytics
    'analytics.specialties.title': 'Аналитика специальностей',
    'analytics.specialties.subtitle': 'Реальные данные о трудоустройстве выпускников. На основе опросов выпускников белорусских вузов.',
    'analytics.specialties.selectUni': 'Университет',
    'analytics.specialties.selectSpec': 'Специальность',
    'analytics.specialties.employmentRate': 'Трудоустройство',
    'analytics.specialties.avgSearchTime': 'Среднее время поиска',
    'analytics.specialties.avgSalary': 'Средняя зарплата',
    'analytics.specialties.inSpecialtyRate': 'Работа по специальности',
    'analytics.specialties.countries': 'Страны трудоустройства',
    'analytics.specialties.topEmployers': 'Топ работодатели',
    'analytics.specialties.empty': 'Выберите университет и специальность для просмотра аналитики',
    'analytics.specialties.share': 'Доля',
    'analytics.specialties.months': 'мес.',
    // Career Map
    'careerMap.title': 'Карта карьер выпускников',
    'careerMap.subtitle': 'Куда идут работать выпускники? Распределение по сферам и топ работодатели.',
    'careerMap.selectSpec': 'Специальность',
    'careerMap.statGraduates': 'Выпускников',
    'careerMap.statFields': 'Сфер деятельности',
    'careerMap.statCountries': 'Стран трудоустройства',
    'careerMap.chartDistribution': 'Распределение по сферам',
    'careerMap.chartEmployers': 'Топ работодатели',
    'careerMap.chartGeography': 'География трудоустройства',
    'careerMap.share': 'Доля',
    'careerMap.graduates': 'Выпускников',
    // Profile additions
    'profile.add': 'Добавить',
    'profile.proficiency.beginner': 'Начальный',
    'profile.proficiency.intermediate': 'Средний',
    'profile.proficiency.advanced': 'Продвинутый',
    'profile.proficiency.expert': 'Эксперт',
    'profile.cefr.a1': 'A1 — Начальный',
    'profile.cefr.a2': 'A2 — Элементарный',
    'profile.cefr.b1': 'B1 — Средний',
    'profile.cefr.b2': 'B2 — Выше среднего',
    'profile.cefr.c1': 'C1 — Продвинутый',
    'profile.cefr.c2': 'C2 — В совершенстве',
    'profile.skillNameRequired': 'Введите название навыка',
    'profile.languageNameRequired': 'Введите название языка',
    'profile.projectTitleRequired': 'Введите название проекта',
    'profile.certNameRequired': 'Введите название сертификата',
    'profile.certIssuerRequired': 'Введите организацию',
    'profile.present': 'настоящее время',
    'profile.open': 'Открыть',
    'profile.verify': 'Подтвердить',
    // Professions (additional)
    'professions.allCategories': 'Все категории',
    'professions.retry': 'Попробовать снова',
  },
  en: {
    'profile.title': 'Profile',
    'profile.back': 'Back',
    'profile.email': 'Email',
    'profile.role': 'Role',
    'profile.admin': 'Administrator',
    'profile.user': 'User',
    'profile.appearance': 'Appearance',
    'profile.appearanceDesc': 'Choose theme',
    'profile.theme.light': 'Light',
    'profile.theme.dark': 'Dark',
    'profile.theme.highContrast': 'High Contrast',
    'profile.language': 'Interface Language',
    'profile.languageDesc': 'Choose interface language',
    'profile.actions': 'Actions',
    'profile.adminPanel': 'Go to Admin Panel',
    'profile.changePassword': 'Change Password',
    'profile.logout': 'Log Out',
    'profile.logoutSuccess': 'Logged out',
    'profile.logoutSuccessDesc': 'You have successfully logged out.',
    'profile.loading': 'Loading...',
    'profile.university': 'University',
    'profile.universityDesc': 'Your university and specialty',
    'profile.faculty': 'Faculty',
    'profile.specialty': 'Specialty',
    'profile.course': 'Course',
    'profile.graduationYear': 'Graduation Year',
    'profile.verification': 'Verification',
    'profile.verified': 'Verified',
    'profile.notVerified': 'Not Verified',
    'profile.editUniversity': 'Edit',
    'profile.fillUniversity': 'Fill Profile',
    'profile.noUniversity': 'No university selected. Fill your profile to get personalized recommendations.',
    'profile.digitalProfile': 'Digital Profile',
    'profile.digitalProfileDesc': 'Skills, languages, projects and certificates',
    'profile.skills': 'Skills',
    'profile.languages': 'Languages',
    'profile.projects': 'Projects',
    'profile.certificates': 'Certificates',
    'profile.addSkill': 'Add Skill',
    'profile.addLanguage': 'Add Language',
    'profile.addProject': 'Add Project',
    'profile.addCertificate': 'Add Certificate',
    'profile.editSkill': 'Edit Skill',
    'profile.editLanguage': 'Edit Language',
    'profile.editProject': 'Edit Project',
    'profile.editCertificate': 'Edit Certificate',
    'profile.skillName': 'Name',
    'profile.proficiencyLevel': 'Proficiency Level',
    'profile.languageName': 'Language',
    'profile.cefrLevel': 'CEFR Level',
    'profile.projectTitle': 'Title *',
    'profile.projectRole': 'Role',
    'profile.projectDescription': 'Description',
    'profile.projectUrl': 'URL',
    'profile.projectStartDate': 'Start Date',
    'profile.projectEndDate': 'End Date',
    'profile.certName': 'Name *',
    'profile.certIssuer': 'Issuer *',
    'profile.certUrl': 'URL',
    'profile.certIssueDate': 'Issue Date',
    'profile.certExpiryDate': 'Expiry Date',
    'profile.skillsEmpty': 'No skills added. Add at least 3-5 skills to improve your profile.',
    'profile.languagesEmpty': 'No languages added.',
    'profile.projectsEmpty': 'No projects added.',
    'profile.certificatesEmpty': 'No certificates added.',
    'profile.skillAdded': 'Skill added',
    'profile.skillUpdated': 'Skill updated',
    'profile.skillDeleted': 'Skill deleted',
    'profile.languageAdded': 'Language added',
    'profile.languageUpdated': 'Language updated',
    'profile.languageDeleted': 'Language deleted',
    'profile.projectAdded': 'Project added',
    'profile.projectUpdated': 'Project updated',
    'profile.projectDeleted': 'Project deleted',
    'profile.certAdded': 'Certificate added',
    'profile.certUpdated': 'Certificate updated',
    'profile.certDeleted': 'Certificate deleted',
    'survey.title': 'Career Trajectory',
    'survey.stillStudying': 'Graduate survey will be available after graduation.',
    'survey.available': 'Survey available ({months} months after graduation)',
    'survey.button': 'Take Survey',
    'survey.employed': 'Are you currently employed?',
    'survey.country': 'Country',
    'survey.company': 'Company',
    'survey.position': 'Position',
    'survey.salary': 'Salary (USD)',
    'survey.inSpecialty': 'Working in your specialty?',
    'survey.submit': 'Submit',
    'survey.thanks': 'Thank you!',
    'survey.saved': 'Your response has been saved',
    'survey.yourPath': 'Your path:',
    'survey.allDone': 'All available surveys completed.',
    'survey.nextMilestone': 'Next: {milestone}',
    'survey.wait': 'Survey not yet available. Come back after graduation.',
    'survey.noData': 'No data to display.',
    'survey.milestone.6months': '6 months after graduation',
    'survey.milestone.12months': '12 months after graduation',
    'survey.milestone.2years': '2 years after graduation',
    'survey.milestone.4years': '4 years after graduation',
    'survey.yes': 'Yes',
    'survey.no': 'No',
    'survey.cancel': 'Cancel',
    'survey.sending': 'Sending...',
    'survey.employedError': 'Error',
    'survey.employedErrorDesc': 'Please answer the employment question',
    'survey.error': 'Error',
    'survey.dialogTitle': 'Graduate Survey',
    'survey.notEmployed': 'Not employed',
    'survey.shortMonths': 'mo',
    'survey.shortYears': 'yr',
    // Survey Landing
    'surveyLanding.badge': 'Graduate Survey',
    'surveyLanding.title': 'End-of-Course Questionnaire',
    'surveyLanding.subtitle': 'Your study and employment experience matters. Take the survey to help future students make informed choices.',
    'surveyLanding.ctaProfile': 'Take the survey',
    'surveyLanding.ctaRegister': 'Sign up',
    'surveyLanding.ctaQuiz': 'Take the career quiz',
    'surveyLanding.howItWorksTitle': 'How it works',
    'surveyLanding.howItWorksDesc': 'We reach out to you at set intervals after graduation to learn how your career is developing.',
    'surveyLanding.milestone0desc': 'First impressions of work and early job search',
    'surveyLanding.milestone1desc': 'Work adaptation, first career decisions',
    'surveyLanding.milestone2desc': 'Career growth, job changes, skill expansion',
    'surveyLanding.milestone3desc': 'Established career, leadership roles, expectations vs reality',
    'surveyLanding.whyTitle': 'Why it matters',
    'surveyLanding.whyDesc': 'Your answers help prospective students and current students make informed decisions.',
    'surveyLanding.benefit1Title': 'For future students',
    'surveyLanding.benefit1Desc': 'Applicants will see real data on employment rates and salaries for each specialty.',
    'surveyLanding.benefit2Title': 'For universities',
    'surveyLanding.benefit2Desc': 'Universities get feedback to improve their educational programmes.',
    'surveyLanding.benefit3Title': 'For the job market',
    'surveyLanding.benefit3Desc': 'Employers see which skills and competencies are in demand.',
    'surveyLanding.statsTitle': 'Become part of the data that changes education',
    'surveyLanding.statsDesc': 'Every response helps build a more accurate picture of the labour market and education in Belarus.',
    'surveyLanding.statsCta': 'Take the survey',
    'surveyLanding.stat1Label': 'Survey stages',
    'surveyLanding.stat2Label': 'Confidential',
    'surveyLanding.stat3Label': 'Languages',
    'surveyLanding.stat4Label': 'Time to complete',
    'surveyLanding.faqTitle': 'Frequently Asked Questions',
    'surveyLanding.faq1q': 'Who can take the survey?',
    'surveyLanding.faq1a': 'The survey is available to all graduates of Belarusian universities at least 6 months after graduation.',
    'surveyLanding.faq2q': 'How often will I receive surveys?',
    'surveyLanding.faq2a': 'Surveys are sent 4 times: at 6 months, 12 months, 2 years and 4 years after graduation. This tracks your career development over time.',
    'surveyLanding.faq3q': 'Will my personal data be published?',
    'surveyLanding.faq3a': 'No. All data is aggregated and anonymised. Only general statistics are published, without any personal information.',
    'surveyLanding.faq4q': 'Can I skip the survey?',
    'surveyLanding.faq4a': 'Yes, you can choose not to respond. However, your contribution helps create a more accurate picture for future students.',
    'surveyLanding.finalTitle': 'Your experience — your contribution to the future of education',
    'surveyLanding.finalDesc': 'Take the survey and help make education in Belarus more transparent and result-oriented.',
    'surveyLanding.cvHint': 'You can also use the information you enter in the questionnaire (language skills, IT skills, educational background) to create your CV.',
    'surveyLanding.card1Title': 'Already have an account?',
    'surveyLanding.card1Desc': 'Log in to your profile and fill in the end-of-course questionnaire. It takes no more than 10 minutes.',
    'surveyLanding.loginCta': 'Log in and fill in the questionnaire',
    'surveyLanding.card2Title': 'Not registered yet?',
    'surveyLanding.card2Desc': 'Create your profile with information about your specialty, fill in the questionnaire and enter your CV into the GradPath database.',
    'surveyLanding.quizTitle': 'Career Guidance Quiz',
    'surveyLanding.quizDesc': 'Not sure about your choice of specialty? Take our quiz to find out which fields of study suit you best.',
    'surveyLanding.supportTitle': 'Any doubts or questions?',
    'surveyLanding.supportDesc': 'If you have any concerns or questions about the questionnaire, visit the FAQs section or contact us.',
    'surveyLanding.faqLink': 'Frequently Asked Questions',
    'surveyLanding.contactLink': 'Contact us',
    'surveyLanding.sidebar.main': 'For Students and Graduates',
    'surveyLanding.sidebar.questionnaire': 'The end-of-course questionnaire',
    'surveyLanding.sidebar.register': 'Register to GradPath',
    'surveyLanding.sidebar.quiz': 'Career Guidance Quiz',
    'surveyLanding.sidebar.internships': 'Internships',
    'surveyLanding.sidebar.events': 'Events',
    'surveyLanding.sidebar.faq': 'FAQs and support',
    'surveyLanding.introBold': 'Are you about to graduate or are you completing a postgraduate programme?',
    'surveyLanding.introText': 'Fill in the questionnaire if you are studying at one of our partner universities. Bachelor\'s, Master\'s, PhD — just before ending your academic career, you have the opportunity to express your opinion on the educational path you are about to complete.',
    'surveyLanding.ctaSectionTitle': 'Fill in the questionnaire:',
    'surveyLanding.doubtsTitle': 'Any doubts about the questionnaire?',
    'surveyLanding.doubtsDesc': 'We created the "FAQs and support" section, just in case you need some help.',
    'nav.home': 'Home',
    'nav.analytics': 'Analytics',
    'hero.title': 'All about Higher Education',
    'hero.chooseUni': 'Choose University',
    'hero.forApplicants': 'For Applicants',
    'hero.analytics': 'Analytics',
    'hero.register': 'Register',
    'hero.search': 'Search university or specialty...',
    'hero.noResults': 'No universities found',
    'hero.unis': 'Universities',
    'hero.vacancies': 'Vacancies in database',
    'hero.sources': 'Data sources',
    'hero.dataNotice': 'Data obtained from open sources: rabota.by, university websites',
    'footer.statistics': 'Statistics',
    'footer.universities': 'Universities',
    'footer.dataAnalytics': 'Data & Analytics',
    'footer.about': 'About',
    'footer.support': 'Support',
    'footer.internships': 'Internships',
    'footer.events': 'Events',
    'footer.careerMap': 'Career Map',
    'footer.blog': 'Blog',
    'footer.team': 'Team',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.aboutProject': 'About Us',
    'footer.admission': 'Admission',
    'footer.analytics': 'Analytics',
    'footer.helpCenter': 'Help Center',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.services': 'Our Services',
    'footer.careerQuiz': 'Career Quiz',
    'footer.surveyLanding': 'Graduate Survey',
    'footer.professionSelection': 'Profession Selection',
    'footer.students': 'For Students',
    'quickLinks.forApplicants': 'For Applicants',
    'quickLinks.forApplicantsDesc': 'Passing scores, specialties, application deadlines',
    'quickLinks.forStudents': 'For Students',
    'quickLinks.forStudentsDesc': 'Job market, salaries, experience requirements',
    'quickLinks.statistics': 'Statistics',
    'quickLinks.statisticsDesc': 'Vacancies, salaries, ML labor market analysis',
    'quickLinks.admission': 'Admission',
    'quickLinks.admissionDesc': 'Past years scores, enrollment statistics',
    'unis.title': 'Choose Your University.',
    'unis.subtitle': 'Information about state universities of Belarus.',
    'unis.inCatalog': 'In catalog',
    'unis.universities': 'universities',
    'unis.totalInRB': 'Total in RB',
    'unis.institutions': 'HE institutions',
    'unis.avgScore': 'Average score',
    'unis.forAdmission': 'for admission',
    'unis.sourceNote': 'Data sources: Average passing scores are for 2025.',
    'applicants.title': 'Choose Your Future Consciously',
    'applicants.subtitle': 'Compare universities, specialties and learn about real employment prospects.',
    'applicants.badge': 'For Applicants',
    'applicants.unis': 'universities',
    'applicants.unisDesc': 'Detailed information about leading universities in Belarus',
    'applicants.jobMarket': 'Job Market',
    'applicants.jobMarketDesc': 'Analysis of vacancies and specialty demand',
    'applicants.demand': 'Market Demand',
    'applicants.demandDesc': 'Analysis of specialty demand',
    'students.title': 'Prepare for the Job Market',
    'students.subtitle': 'Find out which skills are in demand, how much employers pay.',
    'students.badge': 'For Students',
    'students.jobMarket': 'Job Market',
    'students.jobMarketDesc': 'Current vacancy and salary statistics',
    'students.criteria': 'Important Criteria',
    'students.criteriaDesc': 'ML analysis of successful employment factors',
    'students.growth': 'Career Growth',
    'students.growthDesc': 'Career paths in different professions',
    'market.title': 'Job Market',
    'market.titleValue': 'Know Your Worth.',
    'market.vacancies': 'vacancies',
    'market.high': 'high',
    'market.medium': 'medium',
    'market.low': 'low',
    'market.up': 'growing',
    'market.noExperience': 'No experience',
    'market.years': 'years',
    'market.analysis': 'Analysis of {count} vacancies from rabota.by.',
    'market.updated': 'Updated',
    'category.it': 'IT',
    'category.medicine': 'Medicine',
    'category.engineering': 'Engineering',
    'category.economics': 'Economics',
    'category.education': 'Education',
    'category.law': 'Law',
    'professions.title': 'In-Demand Professions',
    'professions.subtitle': 'Top specialties by number of vacancies',
    'professions.all': 'All',
    'professions.highDemand': 'High demand',
    'professions.mediumDemand': 'Medium demand',
    'professions.lowDemand': 'Low demand',
    'professions.workers': 'Workers',
    'professions.employees': 'Employees',
    'professions.specialists': 'Specialists',
    'professions.loadError': 'Failed to load profession data.',
    'analysis.rocAuc': 'ROC-AUC',
    'analysis.accuracyVal': 'Accuracy',
    'analysis.accuracyDesc': 'Proportion of correct predictions',
    'analysis.precisionVal': 'Precision',
    'analysis.precisionDesc': 'Positive predictive value',
    'analysis.recallVal': 'Recall',
    'analysis.recallDesc': 'True positive rate',
    'stats.title': 'Labor Market Data',
    'stats.subtitle': 'Complete analytics of vacancies, salaries and predictions.',
    'stats.vacancies': 'Vacancies',
    'stats.salaries': 'Salaries',
    'stats.mlAnalysis': 'ML Analysis',
    'stats.methodology': 'Methodology',
    'stats.vacanciesAnalytics': 'Labor Market Analytics',
    'stats.vacanciesAnalyticsDesc': 'Data from rabota.by',
    'stats.totalVacancies': 'Total vacancies',
    'stats.byCategories': 'by {count} categories',
    'stats.topDirection': 'Top direction',
    'stats.noData': 'No data',
    'stats.vacanciesCount': 'vacancies',
    'stats.avgSalary': 'Average salary',
    'stats.categories': 'Categories',
    'stats.directions': 'directions',
    'stats.detailedStats': 'Detailed statistics by direction',
    'stats.category': 'Category',
    'stats.vacanciesShort': 'Vacancies',
    'stats.avgSalaryShort': 'Avg salary',
    'stats.range': 'Range',
    'stats.allVacancies': 'All vacancies',
    'stats.vacancy': 'Vacancy',
    'stats.company': 'Company',
    'stats.city': 'City',
    'stats.salary': 'Salary',
    'stats.source': 'Source',
    // Salary Statistics
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.year': 'Year',
    'common.noData': 'N/A',
    'uni.notFound': 'University not found',
    'uni.notFoundDesc': 'Unfortunately, information about this university is not available.',
    'uni.backToList': 'Back to list',
    'uni.about': 'About university',
    'uni.website': 'Website',
    'uni.scores': 'Scores',
    'uni.faculties': 'faculties',
    'uni.specialties': 'specialties',
    'admission.title': 'Admission Statistics',
    'admission.subtitle': 'Historical data on passing scores and number of places',
    'admission.allYears': 'All years',
    'admission.allUniversities': 'All universities',
    'admission.allFaculties': 'All faculties',
    'admission.university': 'University',
    'admission.faculty': 'Faculty',
    'admission.activeFilters': 'Active filters',
    'admission.budgetPlaces': 'Budget places',
    'admission.paidPlaces': 'Paid places',
    'admission.avgScore': 'Average score',
    'admission.competition': 'Competition (pers/place)',
    'admission.table': 'Table',
    'admission.charts': 'Charts',
    'admission.comparison': 'Year comparison',
    'admission.detailStats': 'Detailed statistics by specialty',
    'admission.detailStatsDesc': 'Data on passing scores and number of places',
    'admission.specialty': 'Specialty',
    'admission.uni': 'University',
    'admission.year': 'Year',
    'admission.budget': 'Budget',
    'admission.paid': 'Paid',
    'admission.minScore': 'Min. score',
    'admission.avgScoreShort': 'Avg. score',
    'admission.applications': 'Applications',
    'admission.noData': 'No data to display.',
    'admission.noDataDesc': 'Data is loaded from the database. Make sure the admission_stats table is populated.',
    'admission.placesDynamics': 'Number of places dynamics',
    'admission.placesDynamicsDesc': 'Budget and paid places by years',
    'admission.scoreDynamics': 'Passing scores dynamics',
    'admission.scoreDynamicsDesc': 'Average passing score by years',
    'admission.minScores': 'Minimum passing scores',
    'admission.minScoresDesc': 'Minimum score dynamics by years',
    'admission.noChartData': 'No data for chart',
    'admission.comparisonTitle': 'Passing scores comparison by years',
    'admission.comparisonDesc': 'Select a specialty for detailed comparison of indicators over different years',
    'admission.comparisonNeedData': 'Multiple years of data needed for comparison',
    'admission.selectAllYears': 'Select "All years" in the filter to view comparison',
    'admission.budgetShort': 'Budget',
    'admission.applicationsShort': 'Applications',
    'admission.dataSource': 'Data source:',
    'admission.dataSourceDesc': 'Statistics is loaded from the database. Use parsing in admin panel or add data manually. Only real data from admission_stats table is displayed.',
    'admission.yearBadge': 'year',
    // Internships
    'internships.title': 'Internships for Students',
    'internships.subtitle': 'Current internships and vacancies for students and graduates in Belarus.',
    'internships.searchPlaceholder': 'Search by title or company...',
    'internships.filterDirection': 'Direction',
    'internships.filterCity': 'City',
    'internships.filterType': 'Type',
    'internships.allDirections': 'All directions',
    'internships.allCities': 'All cities',
    'internships.allTypes': 'All types',
    'internships.typePaid': 'Paid',
    'internships.typeUnpaid': 'Unpaid',
    'internships.typeUnknown': 'To be confirmed',
    'internships.badgePaid': 'Paid',
    'internships.badgeUnpaid': 'Unpaid',
    'internships.badgeUnknown': 'TBC',
    'internships.statsTotal': 'Total internships',
    'internships.statsPaid': 'Paid',
    'internships.statsIt': 'IT internships',
    'internships.statsCompanies': 'Companies',
    'internships.salaryNotSpecified': 'Not specified',
    'internships.salaryFrom': 'from {value}',
    'internships.salaryTo': 'up to {value}',
    'internships.today': 'Today',
    'internships.yesterday': 'Yesterday',
    'internships.daysAgo': '{days} days ago',
    'internships.apply': 'Apply',
    'internships.soon': 'Coming soon',
    'internships.empty': 'No internships found matching your request',
    'internships.resetFilters': 'Reset filters',
    'internships.loadError': 'Failed to load internships',
    'internships.retry': 'Retry',
    // Events
    'events.title': 'Career Events',
    'events.subtitle': 'Job fairs, open days, meetups and workshops for students and graduates.',
    'events.searchPlaceholder': 'Search by title or organizer...',
    'events.filterType': 'Type',
    'events.filterCity': 'City',
    'events.filterFormat': 'Format',
    'events.allTypes': 'All types',
    'events.allCities': 'All cities',
    'events.allFormats': 'All formats',
    'events.statsTotal': 'Total events',
    'events.statsUpcoming': 'Upcoming',
    'events.statsOrganizers': 'Organizers',
    'events.statsCities': 'Cities',
    'events.tabUpcoming': 'Upcoming',
    'events.tabAll': 'All',
    'events.formatOffline': 'Offline',
    'events.formatOnline': 'Online',
    'events.formatHybrid': 'Hybrid',
    'events.typeCareerFair': 'Job Fair',
    'events.typeOpenDay': 'Open Day',
    'events.typeMeetup': 'Meetup',
    'events.typeWorkshop': 'Workshop',
    'events.typeLecture': 'Lecture',
    'events.typeOther': 'Other',
    'events.orgCompany': 'Company',
    'events.orgUniversity': 'University',
    'events.orgStudentOrg': 'Student Org',
    'events.orgOther': 'Other',
    'events.register': 'Register',
    'events.soon': 'Coming soon',
    'events.empty': 'No events found matching your request',
    'events.resetFilters': 'Reset filters',
    'events.loadError': 'Failed to load events',
    'events.retry': 'Retry',
    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Articles about career, education, admission and labor market in Belarus.',
    'blog.searchPlaceholder': 'Search articles...',
    'blog.allTags': 'All',
    'blog.readMore': 'Read more',
    'blog.empty': 'No articles found matching your request',
    'blog.resetFilters': 'Reset filters',
    'blog.loadError': 'Failed to load articles',
    'blog.retry': 'Retry',
    'blog.backToList': 'Back to blog',
    'blog.notFound': 'Article not found',
    // Specialty Analytics
    'analytics.specialties.title': 'Specialty Analytics',
    'analytics.specialties.subtitle': 'Real employment data of graduates. Based on surveys of Belarusian university graduates.',
    'analytics.specialties.selectUni': 'University',
    'analytics.specialties.selectSpec': 'Specialty',
    'analytics.specialties.employmentRate': 'Employment Rate',
    'analytics.specialties.avgSearchTime': 'Average Search Time',
    'analytics.specialties.avgSalary': 'Average Salary',
    'analytics.specialties.inSpecialtyRate': 'Working in Specialty',
    'analytics.specialties.countries': 'Employment Countries',
    'analytics.specialties.topEmployers': 'Top Employers',
    'analytics.specialties.empty': 'Select a university and specialty to view analytics',
    'analytics.specialties.share': 'Share',
    'analytics.specialties.months': 'mo.',
    // Career Map
    'careerMap.title': 'Graduate Career Map',
    'careerMap.subtitle': 'Where do graduates work? Distribution by industry and top employers.',
    'careerMap.selectSpec': 'Specialty',
    'careerMap.statGraduates': 'Graduates',
    'careerMap.statFields': 'Fields',
    'careerMap.statCountries': 'Countries',
    'careerMap.chartDistribution': 'Distribution by Industry',
    'careerMap.chartEmployers': 'Top Employers',
    'careerMap.chartGeography': 'Employment Geography',
    'careerMap.share': 'Share',
    'careerMap.graduates': 'Graduates',
    // Profile additions
    'profile.add': 'Add',
    'profile.proficiency.beginner': 'Beginner',
    'profile.proficiency.intermediate': 'Intermediate',
    'profile.proficiency.advanced': 'Advanced',
    'profile.proficiency.expert': 'Expert',
    'profile.cefr.a1': 'A1 — Beginner',
    'profile.cefr.a2': 'A2 — Elementary',
    'profile.cefr.b1': 'B1 — Intermediate',
    'profile.cefr.b2': 'B2 — Upper Intermediate',
    'profile.cefr.c1': 'C1 — Advanced',
    'profile.cefr.c2': 'C2 — Proficient',
    'profile.skillNameRequired': 'Enter skill name',
    'profile.languageNameRequired': 'Enter language name',
    'profile.projectTitleRequired': 'Enter project title',
    'profile.certNameRequired': 'Enter certificate name',
    'profile.certIssuerRequired': 'Enter issuer name',
    'profile.present': 'present',
    'profile.open': 'Open',
    'profile.verify': 'Verify',
    // Professions (additional)
    'professions.allCategories': 'All categories',
    'professions.retry': 'Try again',
  },
  be: {
    'profile.title': 'Профіль',
    'profile.back': 'Назад',
    'profile.email': 'Email',
    'profile.role': 'Роля',
    'profile.admin': 'Адміністратар',
    'profile.user': 'Карыстальнік',
    'profile.appearance': 'Знешні выгляд',
    'profile.appearanceDesc': 'Выберыце тэму афармлення',
    'profile.theme.light': 'Светлая',
    'profile.theme.dark': 'Цёмная',
    'profile.theme.highContrast': 'Для слабабачных',
    'profile.language': 'Мова інтэрфейсу',
    'profile.languageDesc': 'Выберыце мову інтэрфейсу',
    'profile.actions': 'Дзеянні',
    'profile.adminPanel': 'Перайсці ѡ адмін-панэль',
    'profile.changePassword': 'Змяніць пароль',
    'profile.logout': 'Выйсці з акаунта',
    'profile.logoutSuccess': 'Выход выкананы',
    'profile.logoutSuccessDesc': 'Вы паспяхова выйшлі з акаунта.',
    'profile.loading': 'Загрузка...',
    'profile.university': 'Універсітэт',
    'profile.universityDesc': 'Ваш універсітэт і спецыяльнасць',
    'profile.faculty': 'Факультэт',
    'profile.specialty': 'Спецыяльнасць',
    'profile.course': 'Курс',
    'profile.graduationYear': 'Год выпуску',
    'profile.verification': 'Верыфікацыя',
    'profile.verified': 'Верыфікаваны',
    'profile.notVerified': 'Не верыфікаваны',
    'profile.editUniversity': 'Рэдагаваць',
    'profile.fillUniversity': 'Запоўніць профіль',
    'profile.noUniversity': 'Універсітэт не пазначаны. Запоўніце профіль, каб атрымліваць персанальныя рэкамендацыі.',
    'profile.digitalProfile': 'Лічбавы профіль',
    'profile.digitalProfileDesc': 'Навыкі, мовы, праекты і сертыфікаты',
    'profile.skills': 'Навыкі',
    'profile.languages': 'Мовы',
    'profile.projects': 'Праекты',
    'profile.certificates': 'Сертыфікаты',
    'profile.addSkill': 'Дадаць навык',
    'profile.addLanguage': 'Дадаць мову',
    'profile.addProject': 'Дадаць праект',
    'profile.addCertificate': 'Дадаць сертыфікат',
    'profile.editSkill': 'Рэдагаваць навык',
    'profile.editLanguage': 'Рэдагаваць мову',
    'profile.editProject': 'Рэдагаваць праект',
    'profile.editCertificate': 'Рэдагаваць сертыфікат',
    'profile.skillName': 'Назва',
    'profile.proficiencyLevel': 'Узровень валодання',
    'profile.languageName': 'Мова',
    'profile.cefrLevel': 'Узровень (CEFR)',
    'profile.projectTitle': 'Назва *',
    'profile.projectRole': 'Роля',
    'profile.projectDescription': 'Апісанне',
    'profile.projectUrl': 'Спасылка',
    'profile.projectStartDate': 'Дата пачатку',
    'profile.projectEndDate': 'Дата заканчэння',
    'profile.certName': 'Назва *',
    'profile.certIssuer': 'Арганізацыя *',
    'profile.certUrl': 'Спасылка',
    'profile.certIssueDate': 'Дата выдачы',
    'profile.certExpiryDate': 'Тэрмін дзеяння',
    'profile.skillsEmpty': 'Навыкі не дададзены. Дадайце хаця б 3-5 навыкаў для паляпшэння профілю.',
    'profile.languagesEmpty': 'Мовы не дададзены.',
    'profile.projectsEmpty': 'Праекты не дададзены.',
    'profile.certificatesEmpty': 'Сертыфікаты не дададзены.',
    'profile.skillAdded': 'Навык дададзены',
    'profile.skillUpdated': 'Навык абноўлены',
    'profile.skillDeleted': 'Навык выдалены',
    'profile.languageAdded': 'Мова дададзена',
    'profile.languageUpdated': 'Мова абноўлена',
    'profile.languageDeleted': 'Мова выдалена',
    'profile.projectAdded': 'Праект дададзены',
    'profile.projectUpdated': 'Праект абноўлены',
    'profile.projectDeleted': 'Праект выдалены',
    'profile.certAdded': 'Сертыфікат дададзены',
    'profile.certUpdated': 'Сертыфікат абноўлены',
    'profile.certDeleted': 'Сертыфікат выдалены',
    'survey.title': 'Карьерная траекторыя',
    'survey.stillStudying': 'Апытанне выпускнікоў будзе даступна пасля заканчэння ўніверсітэта.',
    'survey.available': 'Апытанне даступна ({months} мес. пасля выпуску)',
    'survey.button': 'Прайсці апытанне',
    'survey.employed': 'Ці працуеце вы зараз?',
    'survey.country': 'Краіна',
    'survey.company': 'Кампанія',
    'survey.position': 'Пасада',
    'survey.salary': 'Зарплата (у USD)',
    'survey.inSpecialty': 'Працуеце па спецыяльнасці?',
    'survey.submit': 'Адправіць',
    'survey.thanks': 'Дзякуй!',
    'survey.saved': 'Ваш адказ захаваны',
    'survey.yourPath': 'Ваш шлях:',
    'survey.allDone': 'Усе даступныя апытанні пройдзены.',
    'survey.nextMilestone': 'Наступнае: {milestone}',
    'survey.wait': 'Апытанне пакуль недаступна. Вяртайцеся пасля выпуску.',
    'survey.noData': 'Няма дадзеных для адлюстравання.',
    'survey.milestone.6months': 'Праз 6 месяцаў пасля выпуску',
    'survey.milestone.12months': 'Праз 12 месяцаў пасля выпуску',
    'survey.milestone.2years': 'Праз 2 гады пасля выпуску',
    'survey.milestone.4years': 'Праз 4 гады пасля выпуску',
    'survey.yes': 'Так',
    'survey.no': 'Не',
    'survey.cancel': 'Адмена',
    'survey.sending': 'Адпраўка...',
    'survey.employedError': 'Памылка',
    'survey.employedErrorDesc': 'Адкажыце на пытанне пра працаўладкаванне',
    'survey.error': 'Памылка',
    'survey.dialogTitle': 'Апытанне выпускніка',
    'survey.notEmployed': 'Не працуе',
    'survey.shortMonths': 'мес',
    'survey.shortYears': 'гады',
    // Survey Landing
    'surveyLanding.badge': 'Апытанне выпускнікоў',
    'surveyLanding.title': 'Апытанне па заканчэнні курса',
    'surveyLanding.subtitle': 'Ваш досвед навучання і працаўладкавання важны. Прайдзіце апытанне, каб дапамагчы будучым студэнтам зрабіць правільны выбар.',
    'surveyLanding.ctaProfile': 'Прайсці апытанне',
    'surveyLanding.ctaRegister': 'Зарэгістравацца',
    'surveyLanding.ctaQuiz': 'Прайсці тэст на прафарыентацыю',
    'surveyLanding.howItWorksTitle': 'Як гэта працуе',
    'surveyLanding.howItWorksDesc': 'Мы звязваемся з вамі праз пэўны час пасля выпуску, каб даведацца, як складваецца ваша кар\'ера.',
    'surveyLanding.milestone0desc': 'Першыя ўражанні пра працу і пошук першых пазіцый',
    'surveyLanding.milestone1desc': 'Адаптацыя на працы, першыя кар\'ерныя рашэнні',
    'surveyLanding.milestone2desc': 'Кар\'ерны рост, змена кампаній, пашырэнне навыкаў',
    'surveyLanding.milestone3desc': 'Стабільная кар\'ера, лідарскія пазіцыі, параўнанне з чаканнямі',
    'surveyLanding.whyTitle': 'Чаму гэта важна',
    'surveyLanding.whyDesc': 'Вашы адказы дапамагаюць будучым студэнтам прымаць усвядомленыя рашэнні.',
    'surveyLanding.benefit1Title': 'Для будучых студэнтаў',
    'surveyLanding.benefit1Desc': 'Абітурыенты ўбачаць рэальныя даныя пра працаўладкаванне і зарплаты па кожнай спецыяльнасці.',
    'surveyLanding.benefit2Title': 'Для ўніверсітэтаў',
    'surveyLanding.benefit2Desc': 'Вузы атрымаюць зваротную сувязь і змогуць палепшыць адукацыйныя праграмы.',
    'surveyLanding.benefit3Title': 'Для рынку працы',
    'surveyLanding.benefit3Desc': 'Працадаўцы ўбачаць, якія навыкі і кампетэнцыі запатрабаваны.',
    'surveyLanding.statsTitle': 'Станьце часткай даных, якія змяняюць адукацыю',
    'surveyLanding.statsDesc': 'Кожны ваш адказ дапамагае стварыць больш дакладную карціну рынку працы і адукацыі ў Беларусі.',
    'surveyLanding.statsCta': 'Прайсці апытанне',
    'surveyLanding.stat1Label': 'Этапаў апытання',
    'surveyLanding.stat2Label': 'Канфідэнцыяльнасць',
    'surveyLanding.stat3Label': 'Мовы',
    'surveyLanding.stat4Label': 'Часу для запаўнення',
    'surveyLanding.faqTitle': 'Часта задаваныя пытанні',
    'surveyLanding.faq1q': 'Хто можа прайсці апытанне?',
    'surveyLanding.faq1a': 'Апытанне даступна для ўсіх выпускнікоў беларускіх універсітэтаў, якія скончылі не менш за 6 месяцаў таму.',
    'surveyLanding.faq2q': 'Як часта будуць прыходзіць апытанні?',
    'surveyLanding.faq2a': 'Апытанні прыходзяць 4 разы: праз 6 месяцаў, 12 месяцаў, 2 гады і 4 гады пасля выпуску. Гэта дазваляе адсочваць дынаміку вашай кар\'еры.',
    'surveyLanding.faq3q': 'Мае даныя будуць апублікаваны?',
    'surveyLanding.faq3a': 'Не. Усе даныя агрэгуюцца і ананімізуюцца. Мы публікуем толькі агульную статыстыку без персанальнай інфармацыі.',
    'surveyLanding.faq4q': 'Можна прапусціць апытанне?',
    'surveyLanding.faq4a': 'Так, вы можаце не адказваць на апытанне. Аднак ваш унёсак дапамагае стварыць больш дакладную карціну для будучых студэнтаў.',
    'surveyLanding.finalTitle': 'Ваш досвед — ваш унёсак у будучыню адукацыі',
    'surveyLanding.finalDesc': 'Прайдзіце апытанне і дапамажыце зрабіць адукацыю ў Беларусі больш празрыстай і арыентаванай на вынік.',
    'surveyLanding.cvHint': 'Вы таксама можаце выкарыстоўваць інфармацыю з анкеты (замежныя мовы, камп\'ютарныя навыкі, адукацыйны бэкграўнд) для стварэння рэзюмэ.',
    'surveyLanding.card1Title': 'Ужо ёсць акаўнт?',
    'surveyLanding.card1Desc': 'Увайдзіце ў свой профіль і запоўніце апытанне па заканчэнні курса. Гэта зойме не больш за 10 хвілін.',
    'surveyLanding.loginCta': 'Увайсці і запоўніць апытанне',
    'surveyLanding.card2Title': 'Яшчэ не зарэгістраваныя?',
    'surveyLanding.card2Desc': 'Стварыце профіль з інфармацыяй пра вашу спецыяльнасць, запоўніце апытанне і размясціце рэзюмэ ў базе GradPath.',
    'surveyLanding.quizTitle': 'Прафарыентацыйны тэст',
    'surveyLanding.quizDesc': 'Не ўпэўненыя ў выбары спецыяльнасці? Прайдзіце наш тэст, каб даведацца, якія напрамкі навучання вам падыходзяць.',
    'surveyLanding.supportTitle': 'Засталіся пытанні?',
    'surveyLanding.supportDesc': 'Калі ў вас ёсць сумненні ці пытанні пра апытанне, наведайце раздзел FAQ ці звяжыцеся з намі.',
    'surveyLanding.faqLink': 'Часта задаваныя пытанні',
    'surveyLanding.contactLink': 'Звязацца з намі',
    'surveyLanding.sidebar.main': 'Для студэнтаў і выпускнікоў',
    'surveyLanding.sidebar.questionnaire': 'Апытанне па заканчэнні курса',
    'surveyLanding.sidebar.register': 'Зарэгістравацца',
    'surveyLanding.sidebar.quiz': 'Прафарыентацыйны тэст',
    'surveyLanding.sidebar.internships': 'Стажыроўкі',
    'surveyLanding.sidebar.events': 'Мерапрыемствы',
    'surveyLanding.sidebar.faq': 'FAQ і падтрымка',
    'surveyLanding.introBold': 'Вы скончваеце навучанне ці завяршаеце магістратуру?',
    'surveyLanding.introText': 'Запоўніце апытанне, калі вы вучыцеся ў адным з універсітэтаў-партнёраў GradPath. Бакалаўрыят, магістратура, аспірантура — перад заканчэннем навучання ёсць магчымасць выказаць сваё меркаванне пра прайсцены адукацыйны шлях.',
    'surveyLanding.ctaSectionTitle': 'Запоўніце апытанне:',
    'surveyLanding.doubtsTitle': 'Засталіся пытанні пра апытанне?',
    'surveyLanding.doubtsDesc': 'Мы стварылі раздзел «FAQ і падтрымка», каб дапамагчы вам.',
    'nav.home': 'Галоўная',
    'nav.analytics': 'Аналітыка',
    'hero.title': 'Усё пра вышэйшую асвету',
    'hero.chooseUni': 'Выбраць ВНУ',
    'hero.forApplicants': 'Для абітурыентаў',
    'hero.analytics': 'Аналітыка',
    'hero.register': 'Рэгістрацыя',
    'hero.search': 'Пошук універсітэта або спецыяльнасці...',
    'hero.noResults': 'Універсітэты не знойдзены',
    'hero.unis': 'ВНУ',
    'hero.vacancies': 'Вакансій у базе',
    'hero.sources': 'Крыніцы дадзеных',
    'hero.dataNotice': 'Дадзеныя атрыманы з адкрытых крыніц',
    'footer.statistics': 'Статыстыка',
    'footer.universities': 'Універсітэты',
    'footer.dataAnalytics': 'Дадзеныя і аналітыка',
    'footer.about': 'Аб праекце',
    'footer.support': 'Падтрымка',
    'footer.internships': 'Стажыроўкі',
    'footer.events': 'Мерапрыемствы',
    'footer.careerMap': "Карта кар'ер",
    'footer.blog': 'Блог',
    'footer.team': 'Каманда',
    'footer.contact': 'Кантакты',
    'footer.faq': 'FAQ',
    'footer.aboutProject': 'Аб нас',
    'footer.admission': 'Паступленне',
    'footer.analytics': 'Аналітыка',
    'footer.helpCenter': 'Цэнтр дапамогі',
    'footer.privacy': 'Палітыка прыватнасці',
    'footer.terms': 'Умовы выкарыстання',
    'footer.allRightsReserved': 'Усе правы абаронены.',
    'footer.services': 'Нашы паслугі',
    'footer.careerQuiz': 'Кар\'ерны тэст',
    'footer.surveyLanding': 'Апытанне выпускнікоў',
    'footer.professionSelection': 'Падбор прафесіі',
    'footer.students': 'Для студэнтаў',
    'quickLinks.forApplicants': 'Для абітурыентаў',
    'quickLinks.forApplicantsDesc': 'Праходныя балы, спецыяльнасці, тэрміны',
    'quickLinks.forStudents': 'Для студэнтаў',
    'quickLinks.forStudentsDesc': 'Рынак працы, зарплаты, вопыт',
    'quickLinks.statistics': 'Статыстыка',
    'quickLinks.statisticsDesc': 'Вакансіі, зарплаты, ML-анализ',
    'quickLinks.admission': 'Паступленне',
    'quickLinks.admissionDesc': 'Балы мінулых гадоў',
    'unis.title': 'Выберыце свой універсітэт.',
    'unis.subtitle': 'Інфармацыя аб дзяржаўных універсітэтах Беларусі.',
    'unis.inCatalog': 'У каталозе',
    'unis.universities': 'універсітэтаў',
    'unis.totalInRB': 'Усяго ѡ РБ',
    'unis.institutions': 'устаноў ВА',
    'unis.avgScore': 'Сярэдні бал',
    'unis.forAdmission': 'для паступлення',
    'unis.sourceNote': 'Крыніцы дадзеных: Сярэднія праходныя балы.',
    'applicants.title': 'Выберыце сваё будучыню свядома',
    'applicants.subtitle': 'Параўнайце універсітэты і спецыяльнасці.',
    'applicants.badge': 'Для абітурыентаў',
    'applicants.unis': 'універсітэтаў',
    'applicants.unisDesc': 'Інфармацыя аб вядучых ВНУ Беларусі',
    'applicants.jobMarket': 'Рынак працы',
    'applicants.jobMarketDesc': 'Аналіз вакансій і попыту',
    'applicants.demand': 'Попыт на рынку',
    'applicants.demandDesc': 'Аналіз попыту спецыяльнасцяў',
    'students.title': 'Падрыхтуйцеся да рынка працы',
    'students.subtitle': 'Даведайцеся, якія навыкі ѡ запаце.',
    'students.badge': 'Для студэнтаў',
    'students.jobMarket': 'Рынак працы',
    'students.jobMarketDesc': 'Статыстыка вакансій і зарплат',
    'students.criteria': 'Важныя крытэры',
    'students.criteriaDesc': 'ML-анализ фактараў працаўладкавання',
    'students.growth': 'Карьерны рост',
    'students.growthDesc': 'Шляхі развіцця',
    'market.title': 'Рынак працы',
    'market.titleValue': 'Ведайце сваю каштоўнасць.',
    'market.vacancies': 'вакансій',
    'market.high': 'высокі',
    'market.medium': 'сярэдні',
    'market.low': 'нізкі',
    'market.up': 'расце',
    'market.noExperience': 'Без вопыту',
    'market.years': 'гадоў',
    'market.analysis': 'Аналіз {count} вакансій з rabota.by.',
    'market.updated': 'Абноўлена',
    'category.it': 'IT',
    'category.medicine': 'Медыцына',
    'category.engineering': 'Інжынерыя',
    'category.economics': 'Эканоміка',
    'category.education': 'Педагогіка',
    'category.law': 'Юрыспрудэнцыя',
    'professions.title': 'Папулярныя прафесіі',
    'professions.subtitle': 'Топ спецыяльнасцяў па вакансіях',
    'professions.all': 'Усе',
    'professions.highDemand': 'Высокі попыт',
    'professions.mediumDemand': 'Сярэдні попыт',
    'professions.lowDemand': 'Нізкі попыт',
    'professions.workers': 'Работнікі',
    'professions.employees': 'Служачыя',
    'professions.specialists': 'Спецыялісты',
    'professions.loadError': 'Не атрымалася загрузіць дадзеныя.',
    'analysis.rocAuc': 'ROC-AUC',
    'analysis.accuracyVal': 'Дакладнасць',
    'analysis.accuracyDesc': 'Доля правільных прагнозаў',
    'analysis.precisionVal': 'Precision',
    'analysis.precisionDesc': 'Дакладнасць станоўчых прагнозаў',
    'analysis.recallVal': 'Recall',
    'analysis.recallDesc': 'Поўнасць выяўлення',
    'stats.title': 'Дадзеныя пра рынак працы',
    'stats.subtitle': 'Поўная аналітыка вакансій і зарплат.',
    'stats.vacancies': 'Вакансіі',
    'stats.salaries': 'Зарплаты',
    'stats.mlAnalysis': 'ML-анализ',
    'stats.methodology': 'Метадалогія',
    'stats.vacanciesAnalytics': 'Аналітыка рынка працы',
    'stats.vacanciesAnalyticsDesc': 'Дадзеныя з rabota.by',
    'stats.totalVacancies': 'Усяго вакансій',
    'stats.byCategories': 'па {count} катэгорыям',
    'stats.topDirection': 'Топ напрамак',
    'stats.noData': 'Няма дадзеных',
    'stats.vacanciesCount': 'вакансій',
    'stats.avgSalary': 'Сярэдняя зарплата',
    'stats.categories': 'Катэгорый',
    'stats.directions': 'напрамкаў',
    'stats.detailedStats': 'Дэтальная статыстыка па напрамкам',
    'stats.category': 'Катэгорыя',
    'stats.vacanciesShort': 'Вакансій',
    'stats.avgSalaryShort': 'Сяр. зарплата',
    'stats.range': 'Дыяпазон',
    'stats.allVacancies': 'Усе вакансіі',
    'stats.vacancy': 'Вакансія',
    'stats.company': 'Кампанія',
    'stats.city': 'Горад',
    'stats.salary': 'Зарплата',
    'stats.source': 'Крыніца',
    // Salary Statistics
    'common.loading': 'Загрузка...',
    'common.error': 'Памылка',
    'common.save': 'Захаваць',
    'common.cancel': 'Адмена',
    'common.year': 'Год',
    'common.noData': 'Н/Д',
    'uni.notFound': 'Універсітэт не знойдзен',
    'uni.notFoundDesc': 'Нажаль, інфармацыя адсутнічае.',
    'uni.backToList': 'Вярнуцца да спісу',
    'uni.about': 'Пра універсітэт',
    'uni.website': 'Сайт',
    'uni.scores': 'Балы',
    'uni.faculties': 'факультэтаў',
    'uni.specialties': 'спецыяльнасцяў',
    'admission.title': 'Статыстыка паступлення',
    'admission.subtitle': 'Гісторычныя дадзеныя аб праходных балах',
    'admission.allYears': 'Усе гады',
    'admission.allUniversities': 'Усе універсітэты',
    'admission.allFaculties': 'Усе факультэты',
    'admission.university': 'Універсітэт',
    'admission.faculty': 'Факультэт',
    'admission.activeFilters': 'Актыўныя фільтры',
    'admission.budgetPlaces': 'Бюджэтных месцаў',
    'admission.paidPlaces': 'Платных месцаў',
    'admission.avgScore': 'Сярэдні бал',
    'admission.competition': 'Конкурс (чал/место)',
    'admission.table': 'Табліца',
    'admission.charts': 'Графікі',
    'admission.comparison': 'Параўнанне па гадах',
    'admission.detailStats': 'Дэтальная статыстыка па спецыяльнасцях',
    'admission.detailStatsDesc': 'Дадзеныя аб праходных балах і колькасці месцаў',
    'admission.specialty': 'Спецыяльнасць',
    'admission.uni': 'Універсітэт',
    'admission.year': 'Год',
    'admission.budget': 'Бюджэт',
    'admission.paid': 'Платное',
    'admission.minScore': 'Мін. бал',
    'admission.avgScoreShort': 'Сяр. бал',
    'admission.applications': 'Заявак',
    'admission.noData': 'Няма дадзеных для адлюстравання.',
    'admission.noDataDesc': 'Дадзеныя загружаюцца з базы. Праверце, што табліца admission_stats запоўнена.',
    'admission.placesDynamics': 'Дынаміка колькасці месцаў',
    'admission.placesDynamicsDesc': 'Бюджэтныя і платныя месцы па гадах',
    'admission.scoreDynamics': 'Дынаміка праходных балаў',
    'admission.scoreDynamicsDesc': 'Сярэдні праходны бал па гадах',
    'admission.minScores': 'Мінімальныя праходныя балы',
    'admission.minScoresDesc': 'Дынаміка мінімальных балаў па гадах',
    'admission.noChartData': 'Няма дадзеных для графіка',
    'admission.comparisonTitle': 'Параўнанне праходных балаў па гадах',
    'admission.comparisonDesc': 'Выберыце спецыяльнасць для дэтальнага параўнання паказчыкаў за розныя гады',
    'admission.comparisonNeedData': 'Для параўнення патрэбны дадзеныя за некалькі гадоў',
    'admission.selectAllYears': 'Выберыце "Усе гады" у фільтры для прагляду параўнання',
    'admission.budgetShort': 'Бюджэт',
    'admission.applicationsShort': 'Заяўкі',
    'admission.dataSource': 'Крыніца дадзеных:',
    'admission.dataSourceDesc': 'Статыстыка загружаецца з базы дадзеных. Для абнаўлення выкарыстоўвайце парсінг у панэлі адміністратара або дадайце дадзеныя ўручную. Адлюстроўваюцца толькі рэальныя дадзеныя з табліцы admission_stats.',
    'admission.yearBadge': 'год',
    // Internships
    'internships.title': 'Стажыроўкі для студэнтаў',
    'internships.subtitle': 'Актуальныя стажыроўкі і вакансіі для студэнтаў і выпускнікоў у Беларусі.',
    'internships.searchPlaceholder': 'Пошук па назве або кампаніі...',
    'internships.filterDirection': 'Напрамак',
    'internships.filterCity': 'Горад',
    'internships.filterType': 'Тып',
    'internships.allDirections': 'Усе напрамкі',
    'internships.allCities': 'Усе гарады',
    'internships.allTypes': 'Усе тыпы',
    'internships.typePaid': 'Платныя',
    'internships.typeUnpaid': 'Без аплаты',
    'internships.typeUnknown': 'Удакладняецца',
    'internships.badgePaid': 'Платна',
    'internships.badgeUnpaid': 'Без аплаты',
    'internships.badgeUnknown': 'Удакладняецца',
    'internships.statsTotal': 'Усяго стажыровак',
    'internships.statsPaid': 'Платна',
    'internships.statsIt': 'IT стажыроўкі',
    'internships.statsCompanies': 'Кампаній',
    'internships.salaryNotSpecified': 'Не пазначана',
    'internships.salaryFrom': 'ад {value}',
    'internships.salaryTo': 'да {value}',
    'internships.today': 'Сёння',
    'internships.yesterday': 'Учора',
    'internships.daysAgo': '{days} дні таму',
    'internships.apply': 'Адгукнуцца',
    'internships.soon': 'Хутка',
    'internships.empty': 'Па вашым запыце нічога не знойдзена',
    'internships.resetFilters': 'Скінуць фільтры',
    'internships.loadError': 'Не атрымалася загрузіць стажыроўкі',
    'internships.retry': 'Паўтарыць',
    // Events
    'events.title': 'Кар\'ерныя мерапрыемствы',
    'events.subtitle': 'Кірмашы вакансій, дні адчыненых дзвярэй, мітапы і воркшопы.',
    'events.searchPlaceholder': 'Пошук па назве або арганізатару...',
    'events.filterType': 'Тып',
    'events.filterCity': 'Горад',
    'events.filterFormat': 'Фармат',
    'events.allTypes': 'Усе тыпы',
    'events.allCities': 'Усе гарады',
    'events.allFormats': 'Усе фарматы',
    'events.statsTotal': 'Усяго мерапрыемстваў',
    'events.statsUpcoming': 'Будучых',
    'events.statsOrganizers': 'Арганізатараў',
    'events.statsCities': 'Гарадоў',
    'events.tabUpcoming': 'Будучыя',
    'events.tabAll': 'Усе',
    'events.formatOffline': 'Афлайн',
    'events.formatOnline': 'Анлайн',
    'events.formatHybrid': 'Гібрыд',
    'events.typeCareerFair': 'Кірмаш вакансій',
    'events.typeOpenDay': 'Дзень адчыненых дзвярэй',
    'events.typeMeetup': 'Мітап',
    'events.typeWorkshop': 'Воркшоп',
    'events.typeLecture': 'Лекцыя',
    'events.typeOther': 'Іншае',
    'events.orgCompany': 'Кампанія',
    'events.orgUniversity': 'ВНУ',
    'events.orgStudentOrg': 'Студ. арганізацыя',
    'events.orgOther': 'Іншае',
    'events.register': 'Запісацца',
    'events.soon': 'Хутка',
    'events.empty': 'Па вашым запыце нічога не знойдзена',
    'events.resetFilters': 'Скінуць фільтры',
    'events.loadError': 'Не атрымалася загрузіць мерапрыемствы',
    'events.retry': 'Паўтарыць',
    // Blog
    'blog.title': 'Блог',
    'blog.subtitle': 'Артыкулы аб кар\'еры, адукацыі, паступленні і рынку працы ў Беларусі.',
    'blog.searchPlaceholder': 'Пошук па артыкулах...',
    'blog.allTags': 'Усе',
    'blog.readMore': 'Чытаць далей',
    'blog.empty': 'Па вашым запыце нічога не знойдзена',
    'blog.resetFilters': 'Скінуць фільтры',
    'blog.loadError': 'Не атрымалася загрузіць артыкулы',
    'blog.retry': 'Паўтарыць',
    'blog.backToList': 'Назад да блогу',
    'blog.notFound': 'Артыкул не знойдзен',
    // Specialty Analytics
    'analytics.specialties.title': 'Аналітыка спецыяльнасцяў',
    'analytics.specialties.subtitle': 'Рэальныя дадзеныя аб працаўладкаванні выпускнікоў беларускіх ВНУ.',
    'analytics.specialties.selectUni': 'Універсітэт',
    'analytics.specialties.selectSpec': 'Спецыяльнасць',
    'analytics.specialties.employmentRate': 'Працаўладкаванне',
    'analytics.specialties.avgSearchTime': 'Сярэдні час пошуку',
    'analytics.specialties.avgSalary': 'Сярэдняя зарплата',
    'analytics.specialties.inSpecialtyRate': 'Праца па спецыяльнасці',
    'analytics.specialties.countries': 'Краіны працаўладкавання',
    'analytics.specialties.topEmployers': 'Топ працадаўцы',
    'analytics.specialties.empty': 'Выберыце універсітэт і спецыяльнасць для прагляду аналітыкі',
    'analytics.specialties.share': 'Доля',
    'analytics.specialties.months': 'мес.',
    // Career Map
    'careerMap.title': "Карта кар'ер выпускнікоў",
    'careerMap.subtitle': "Куды ідуць працаваць выпускнікі? Размеркаванне па сферах і топ працадаўцы.",
    'careerMap.selectSpec': 'Спецыяльнасць',
    'careerMap.statGraduates': 'Выпускнікоў',
    'careerMap.statFields': 'Сфер дзейнасці',
    'careerMap.statCountries': 'Краін працаўладкавання',
    'careerMap.chartDistribution': 'Размеркаванне па сферах',
    'careerMap.chartEmployers': 'Топ працадаўцы',
    'careerMap.chartGeography': 'Геаграфія працаўладкавання',
    'careerMap.share': 'Доля',
    'careerMap.graduates': 'Выпускнікоў',
    // Profile additions
    'profile.add': 'Дадаць',
    'profile.proficiency.beginner': 'Пачатковы',
    'profile.proficiency.intermediate': 'Сярэдні',
    'profile.proficiency.advanced': 'Прасунуты',
    'profile.proficiency.expert': 'Эксперт',
    'profile.cefr.a1': 'A1 — Пачатковы',
    'profile.cefr.a2': 'A2 — Элементарны',
    'profile.cefr.b1': 'B1 — Сярэдні',
    'profile.cefr.b2': 'B2 — Вышэй за сярэдні',
    'profile.cefr.c1': 'C1 — Прасунуты',
    'profile.cefr.c2': 'C2 — Дасканалы',
    'profile.skillNameRequired': 'Увядзіце назву навыка',
    'profile.languageNameRequired': 'Увядзіце назву мовы',
    'profile.projectTitleRequired': 'Увядзіце назву праекта',
    'profile.certNameRequired': 'Увядзіце назву сертыфіката',
    'profile.certIssuerRequired': 'Увядзіце арганізацыю',
    'profile.present': 'цяперашні час',
    'profile.open': 'Адкрыць',
    'profile.verify': 'Пацвердзіць',
    // Professions (additional)
    'professions.allCategories': 'Усе катэгорыі',
    'professions.retry': 'Паспрабаваць зноў',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
      if (stored && ['ru', 'en', 'be'].includes(stored)) {
        return stored;
      }
    }
    return 'ru';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || translations['ru'][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

interface UniversityNameFields {
  short_name?: string | null;
  short_name_en?: string | null;
  short_name_be?: string | null;
  full_name?: string | null;
  full_name_en?: string | null;
  full_name_be?: string | null;
}

interface FacultyNameFields {
  name?: string | null;
  name_en?: string | null;
  name_be?: string | null;
}

export function getUniversityTranslatedName(uni: UniversityNameFields, language: Language): string {
  if (language === 'en' && uni.short_name_en) return uni.short_name_en;
  if (language === 'be' && uni.short_name_be) return uni.short_name_be;
  return uni.short_name || uni.full_name || '';
}

export function getFacultyTranslatedName(fac: FacultyNameFields, language: Language): string {
  if (language === 'en' && fac.name_en) return fac.name_en;
  if (language === 'be' && fac.name_be) return fac.name_be;
  return fac.name || '';
}

export function translateCategory(category: string, language: Language): string {
  const key = `category.${category.toLowerCase().replace(/[^a-z]/g, '')}`;
  const translations: Record<Language, Record<string, string>> = {
    ru: {
      it: 'ИТ',
      medicine: 'Медицина',
      engineering: 'Инженерия',
      economics: 'Экономика',
      education: 'Педагогика',
      law: 'Юриспруденция',
      marketing: 'Маркетинг',
      design: 'Дизайн',
      media: 'Медиа',
      sales: 'Продажи',
      admin: 'Административная работа',
      construction: 'Строительство',
      transport: 'Транспорт',
      production: 'Производство',
      agriculture: 'Сельское хозяйство',
      other: 'Другое',
    },
    en: {
      it: 'IT',
      medicine: 'Medicine',
      engineering: 'Engineering',
      economics: 'Economics',
      education: 'Education',
      law: 'Law',
      marketing: 'Marketing',
      design: 'Design',
      media: 'Media',
      sales: 'Sales',
      admin: 'Administrative',
      construction: 'Construction',
      transport: 'Transport',
      production: 'Production',
      agriculture: 'Agriculture',
      other: 'Other',
    },
    be: {
      it: 'IT',
      medicine: 'Медыцына',
      engineering: 'Інжынерыя',
      economics: 'Эканоміка',
      education: 'Педагогіка',
      law: 'Юрыспрудэнцыя',
      marketing: 'Маркетынг',
      design: 'Дызайн',
      media: 'Медыа',
      sales: 'Продажы',
      admin: 'Адміністрацыйная',
      construction: 'Будаўніцтва',
      transport: 'Транспарт',
      production: 'Вытворчасць',
      agriculture: 'Сельская гаспадарка',
      other: 'Іншае',
    },
  };
  
  const normalizedKey = category.toLowerCase().replace(/[^a-z]/g, '');
  return translations[language][normalizedKey] || category;
}
