import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

export type Language = 'ru' | 'en' | 'be';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'gradpath-language';

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Profile
    'profile.title': 'Профиль',
    'profile.back': 'Назад',
    'profile.email': 'Email',
    'profile.role': 'Роль',
    'profile.admin': 'Администратор',
    'profile.user': 'Пользователь',
    'profile.appearance': 'Внешний вид',
    'profile.appearanceDesc': 'Выберите тему оформления',
    'profile.theme.light': 'Светлая',
    'profile.theme.dark': 'Тёмная',
    'profile.theme.highContrast': 'Для слабовидящих',
    'profile.language': 'Язык интерфейса',
    'profile.languageDesc': 'Выберите язык интерфейса',
    'profile.actions': 'Действия',
    'profile.adminPanel': 'Перейти в админ-панель',
    'profile.changePassword': 'Изменить пароль',
    'profile.logout': 'Выйти из аккаунта',
    'profile.logoutSuccess': 'Выход выполнен',
    'profile.logoutSuccessDesc': 'Вы успешно вышли из аккаунта.',
    'profile.loading': 'Загрузка...',
    // Navigation
    'nav.home': 'Главная',
    'nav.applicants': 'Абитуриентам',
    'nav.students': 'Студентам',
    'nav.analytics': 'Аналитика',
    'nav.admission': 'Поступление',
    // Hero
    'hero.title': 'Всё о высшем образовании',
    'hero.subtitle': 'Справочник для абитуриентов и студентов: университеты, специальности, проходные баллы и реальные данные о рынке труда',
    'hero.chooseUni': 'Выбрать ВУЗ',
    'hero.forApplicants': 'Для абитуриентов',
    'hero.analytics': 'Аналитика',
    'hero.register': 'Регистрация',
    'hero.welcome': 'С возвращением,',
    'hero.continue': 'Продолжите поиск или проверьте избранные вузы в профиле',
    'hero.search': 'Поиск университета или специальности...',
    'hero.noResults': 'Университеты не найдены',
    'hero.unis': 'ВУЗов',
    'hero.vacancies': 'Вакансий в базе',
    'hero.sources': 'Источников данных',
    'hero.dataNotice': 'Данные получены из открытых источников: rabota.by, сайты ВУЗов',
    // Footer
    'footer.statistics': 'Статистика',
    'footer.universities': 'ВУЗы',
    'footer.jobMarket': 'Рынок труда',
    'footer.mlAnalysis': 'ML анализ',
    'footer.dataNote': 'Данные на основе анализа rabota.by и открытых источников • ML-модели обучены на данных 1200+ выпускников',
    // Quick Links
    'quickLinks.title': 'Выбери свой путь',
    'quickLinks.subtitle': 'Данные и инструменты для принятия решений',
    'quickLinks.forApplicants': 'Для абитуриентов',
    'quickLinks.forApplicantsDesc': 'Проходные баллы, специальности, сроки подачи документов',
    'quickLinks.forStudents': 'Для студентов',
    'quickLinks.forStudentsDesc': 'Рынок труда, зарплаты, требования к опыту',
    'quickLinks.statistics': 'Статистика',
    'quickLinks.statisticsDesc': 'Вакансии, зарплаты, ML-анализ рынка труда',
    'quickLinks.admission': 'Поступление',
    'quickLinks.admissionDesc': 'Баллы прошлых лет, статистика зачислений',
    // Universities Section
    'unis.title': 'Выбери свой университет.',
    'unis.subtitle': 'Информация о государственных университетах Беларуси. Указаны средние проходные баллы за 2025 год.',
    'unis.inCatalog': 'В каталоге',
    'unis.universities': 'университетов',
    'unis.totalInRB': 'Всего в РБ',
    'unis.institutions': 'учреждений ВО',
    'unis.avgScore': 'Средний балл',
    'unis.forAdmission': 'для поступления',
    'unis.sourceNote': 'Источники данных: Средние проходные баллы указаны за 2025 год. Данные предоставлены для справки.',
    // Applicants Page
    'applicants.title': 'Выбери своё будущее осознанно',
    'applicants.subtitle': 'Сравни университеты, специальности и узнай реальные перспективы трудоустройства.',
    'applicants.badge': 'Для абитуриентов',
    'applicants.unis': 'университетов',
    'applicants.unisDesc': 'Детальная информация о ведущих вузах Беларуси',
    'applicants.jobMarket': 'Рынок труда',
    'applicants.jobMarketDesc': 'Анализ вакансий и востребованности специальностей',
    'applicants.demand': 'Спрос на рынке',
    'applicants.demandDesc': 'Анализ востребованности специальностей',
    'applicants.comparison': 'Сравнение специальностей',
    'applicants.comparisonSubtitle': 'Востребованность специальностей и карьерный рост по направлениям',
    'applicants.dataWarning': 'О данных на странице',
    'applicants.dataWarningDesc': 'Данные о зарплатах получены на основе анализа вакансий с rabota.by.',
    // Students Page
    'students.title': 'Подготовься к рынку труда',
    'students.subtitle': 'Узнай, какие навыки востребованы, сколько платят работодатели и как построить успешную карьеру.',
    'students.badge': 'Для студентов',
    'students.jobMarket': 'Рынок труда',
    'students.jobMarketDesc': 'Актуальная статистика вакансий и зарплат',
    'students.criteria': 'Важные критерии',
    'students.criteriaDesc': 'ML-анализ факторов успешного трудоустройства',
    'students.growth': 'Карьерный рост',
    'students.growthDesc': 'Пути развития в разных профессиях',
    // Market Section
    'market.title': 'Рынок труда',
    'market.titleValue': 'Знай свою ценность.',
    'market.vacancies': 'вакансий',
    'market.avgSalary': 'Средняя зарплата',
    'market.loading': 'Загрузка...',
    'market.dataFrom': 'Данные загружаются из rabota.by',
    'market.demand': 'Спрос',
    'market.high': 'высокий',
    'market.medium': 'средний',
    'market.low': 'низкий',
    'market.trend': 'Тренд',
    'market.up': 'растёт',
    'market.down': 'падает',
    'market.stable': 'стабильно',
    'market.experience': 'Требуемый опыт',
    'market.noExperience': 'Без опыта',
    'market.years': 'года',
    'market.analysis': 'Анализ {count} вакансий с rabota.by.',
    'market.updated': 'Обновлено',
    // Categories - from database
    'category.it': 'ИТ',
    'category.medicine': 'Медицина',
    'category.engineering': 'Инженерия',
    'category.economics': 'Экономика',
    'category.education': 'Педагогика',
    'category.law': 'Юриспруденция',
    'category.marketing': 'Маркетинг',
    'category.design': 'Дизайн',
    'category.media': 'Медиа',
    'category.sales': 'Продажи',
    'category.admin': 'Административная работа',
    'category.construction': 'Строительство',
    'category.transport': 'Транспорт',
    'category.production': 'Производство',
    'category.agriculture': 'Сельское хозяйство',
    'category.other': 'Другое',
    // Professions Section
    'professions.title': 'Востребованные профессии',
    'professions.subtitle': 'Топ специальностей по количеству вакансий и уровню зарплат',
    'professions.filter': 'Фильтр',
    'professions.all': 'Все',
    'professions.highDemand': 'Высокий спрос',
    'professions.mediumDemand': 'Средний спрос',
    'professions.lowDemand': 'Низкий спрос',
    'professions.category': 'Категория',
    'professions.workers': 'Рабочие',
    'professions.employees': 'Служащие',
    'professions.specialists': 'Специалисты',
    'professions.loadError': 'Не удалось загрузить данные о профессиях.',
    // Analysis Section
    'analysis.title': 'ML-анализ',
    'analysis.subtitle': 'Прогноз трудоустройства на основе машинного обучения',
    'analysis.model': 'Модель',
    'analysis.modelDesc': 'Комбинация XGBoost, LightGBM и RandomForest',
    'analysis.shap': 'SHAP-анализ',
    'analysis.shapDesc': 'Интерпретируемость модели',
    'analysis.features': '12 признаков',
    'analysis.featuresDesc': 'GPA, опыт, ВУЗ, город, стажировки, проекты',
    'analysis.accuracy': 'Точность',
    'analysis.rocAuc': 'ROC-AUC',
    'analysis.selectFaculty': 'Выберите направление',
    'analysis.selectUniversity': 'Выберите университет',
    'analysis.predict': 'Предсказать шансы',
    'analysis.employed': 'Вероятность трудоустройства',
    'analysis.accuracyVal': 'Точность (Accuracy)',
    'analysis.accuracyDesc': 'Доля правильных предсказаний',
    'analysis.precisionVal': 'Precision',
    'analysis.precisionDesc': 'Точность положительных предсказаний',
    'analysis.recallVal': 'Recall',
    'analysis.recallDesc': 'Полнота выявления',
    'analysis.facultyEmploymentRate': 'Направление',
    'analysis.gpaNormalized': 'Средний балл',
    'analysis.experienceNormalized': 'Опыт работы',
    'analysis.cityEconomicFactor': 'Город',
    'analysis.universityPrestige': 'Престиж ВУЗа',
    'analysis.industryGrowthRate': 'Рост индустрии',
    'analysis.compositeMarketScore': 'Рыночный потенциал',
    'analysis.facultyUniversityMatch': 'Совместимость ВУЗ-факультет',
    'analysis.internshipsNormalized': 'Стажировки',
    'analysis.projectsNormalized': 'Проекты',
    'analysis.isotonicCalibration': 'Изотоническая калибровка',
    'analysis.isotonicCalibrationDesc': 'Корректировка вероятностей для более точных прогнозов',
    'stats.title': 'Данные о рынке труда',
    'stats.subtitle': 'Полная аналитика вакансий, зарплат и прогнозы на основе машинного обучения.',
    'stats.vacancies': 'Вакансии',
    'stats.salaries': 'Зарплаты',
    'stats.mlAnalysis': 'ML-анализ',
    'stats.methodology': 'Методология',
    'stats.vacanciesAnalytics': 'Аналитика рынка труда',
    'stats.vacanciesAnalyticsDesc': 'Данные с rabota.by',
    'stats.totalVacancies': 'Всего вакансий',
    'stats.byCategories': 'по {count} категориям',
    'stats.topDirection': 'Топ направление',
    'stats.noData': 'Нет данных',
    'stats.noSearchResults': 'Нет вакансий, соответствующих поиску',
    'stats.vacanciesCount': 'вакансий',
    'stats.avgSalary': 'Средняя зарплата',
    'stats.categories': 'Категорий',
    'stats.directions': 'направлений',
    'stats.detailedStats': 'Детальная статистика по направлениям',
    'stats.category': 'Категория',
    'stats.vacanciesShort': 'Вакансий',
    'stats.avgSalaryShort': 'Ср. зарплата',
    'stats.range': 'Диапазон',
    'stats.allVacancies': 'Все вакансии',
    'stats.vacancy': 'Вакансия',
    'stats.company': 'Компания',
    'stats.city': 'Город',
    'stats.salary': 'Зарплата',
    'stats.source': 'Источник',
    // Salary Statistics
    'salary.title': 'Статистика зарплат',
    'salary.avgByCategory': 'Средняя зарплата по категориям',
    // Auth
    'auth.login': 'Войти',
    'auth.register': 'Регистрация',
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.close': 'Закрыть',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.viewAll': 'Посмотреть все',
    'common.seeMore': 'Подробнее',
    'common.back': 'Назад',
    'common.year': 'Год',
    'common.city': 'Город',
    'common.noData': 'Н/Д',
    // University Detail
    'uni.notFound': 'Университет не найден',
    'uni.notFoundDesc': 'К сожалению, информация о данном университете отсутствует.',
    'uni.backToList': 'Вернуться к списку',
    'uni.about': 'О университете',
    'uni.website': 'Сайт',
    'uni.scores': 'Баллы',
    'uni.faculties': 'факультетов',
    'uni.institutes': 'институтов',
    'uni.specialties': 'специальностей',
    'uni.passingScores': 'Проходные баллы',
    'uni.passingScoresYears': '(2022-2025)',
    'uni.minScore': 'Мин. балл',
    'uni.avgScore': 'Ср. балл',
    'uni.budget': 'Бюджет',
    'uni.paid': 'Платное',
    'uni.places': 'Мест',
    'uni.faculty': 'Факультет',
    'uni.allFaculties': 'Все факультеты и институты',
    'uni.allSpecialties': 'Все специальности',
    'uni.noData': 'Нет данных',
    // Chat
    'chat.placeholder': 'Напишите: "320 баллов, хочу на IT в Минск"...',
    'chat.suggestions': 'Популярные вопросы',
    // Admission Page
    'admission.title': 'Статистика поступления',
    'admission.subtitle': 'Исторические данные о проходных баллах и количестве мест',
    'admission.allYears': 'Все годы',
    'admission.allUniversities': 'Все университеты',
    'admission.allFaculties': 'Все факультеты',
    'admission.university': 'Университет',
    'admission.faculty': 'Факультет',
    'admission.activeFilters': 'Активные фильтры',
    'admission.budgetPlaces': 'Бюджетных мест',
    'admission.paidPlaces': 'Платных мест',
    'admission.avgScore': 'Средний балл',
    'admission.competition': 'Конкурс (чел/место)',
    'admission.table': 'Таблица',
    'admission.charts': 'Графики',
    'admission.comparison': 'Сравнение по годам',
    'admission.detailStats': 'Детальная статистика по специальностям',
    'admission.detailStatsDesc': 'Данные о проходных баллах и количестве мест',
    'admission.specialty': 'Специальность',
    'admission.uni': 'Университет',
    'admission.year': 'Год',
    'admission.budget': 'Бюджет',
    'admission.paid': 'Платное',
    'admission.minScore': 'Мин. балл',
    'admission.avgScoreShort': 'Ср. балл',
    'admission.applications': 'Заявок',
    'admission.noData': 'Нет данных для отображения.',
    'admission.noDataDesc': 'Данные загружаются из базы. Убедитесь, что таблица admission_stats заполнена.',
    'admission.placesDynamics': 'Динамика количества мест',
    'admission.placesDynamicsDesc': 'Бюджетные и платные места по годам',
    'admission.scoreDynamics': 'Динамика проходных баллов',
    'admission.scoreDynamicsDesc': 'Средний проходной балл по годам',
    'admission.minScores': 'Минимальные проходные баллы',
    'admission.minScoresDesc': 'Динамика минимальных баллов по годам',
    'admission.noChartData': 'Нет данных для графика',
    'admission.comparisonTitle': 'Сравнение проходных баллов по годам',
    'admission.comparisonDesc': 'Выберите специальность для детального сравнения показателей за разные годы',
    'admission.comparisonNeedData': 'Для сравнения нужны данные за несколько лет',
    'admission.selectAllYears': 'Выберите "Все годы" в фильтре для просмотра сравнения',
    'admission.budgetShort': 'Бюджет',
    'admission.applicationsShort': 'Заявки',
    'admission.dataSource': 'Источник данных:',
    'admission.dataSourceDesc': 'Статистика загружается из базы данных. Для обновления данных используйте парсинг в панели администратора или добавьте данные вручную. Отображаются только реальные данные из таблицы admission_stats.',
    'admission.yearBadge': 'год',
  },
  en: {
    'profile.title': 'Profile',
    'profile.back': 'Back',
    'profile.email': 'Email',
    'profile.role': 'Role',
    'profile.admin': 'Administrator',
    'profile.user': 'User',
    'profile.appearance': 'Appearance',
    'profile.appearanceDesc': 'Choose theme',
    'profile.theme.light': 'Light',
    'profile.theme.dark': 'Dark',
    'profile.theme.highContrast': 'High Contrast',
    'profile.language': 'Interface Language',
    'profile.languageDesc': 'Choose interface language',
    'profile.actions': 'Actions',
    'profile.adminPanel': 'Go to Admin Panel',
    'profile.changePassword': 'Change Password',
    'profile.logout': 'Log Out',
    'profile.logoutSuccess': 'Logged out',
    'profile.logoutSuccessDesc': 'You have successfully logged out.',
    'profile.loading': 'Loading...',
    'nav.home': 'Home',
    'nav.applicants': 'For Applicants',
    'nav.students': 'For Students',
    'nav.analytics': 'Analytics',
    'nav.admission': 'Admission',
    'hero.title': 'All about Higher Education',
    'hero.subtitle': 'Guide for applicants and students: universities, specialties, passing scores and real labor market data',
    'hero.chooseUni': 'Choose University',
    'hero.forApplicants': 'For Applicants',
    'hero.analytics': 'Analytics',
    'hero.register': 'Register',
    'hero.welcome': 'Welcome back,',
    'hero.continue': 'Continue searching or check saved universities in your profile',
    'hero.search': 'Search university or specialty...',
    'hero.noResults': 'No universities found',
    'hero.unis': 'Universities',
    'hero.vacancies': 'Vacancies in database',
    'hero.sources': 'Data sources',
    'hero.dataNotice': 'Data obtained from open sources: rabota.by, university websites',
    'footer.statistics': 'Statistics',
    'footer.universities': 'Universities',
    'footer.jobMarket': 'Job Market',
    'footer.mlAnalysis': 'ML Analysis',
    'footer.dataNote': 'Data based on rabota.by analysis and open sources',
    'quickLinks.title': 'Choose Your Path',
    'quickLinks.subtitle': 'Data and tools for decision making',
    'quickLinks.forApplicants': 'For Applicants',
    'quickLinks.forApplicantsDesc': 'Passing scores, specialties, application deadlines',
    'quickLinks.forStudents': 'For Students',
    'quickLinks.forStudentsDesc': 'Job market, salaries, experience requirements',
    'quickLinks.statistics': 'Statistics',
    'quickLinks.statisticsDesc': 'Vacancies, salaries, ML labor market analysis',
    'quickLinks.admission': 'Admission',
    'quickLinks.admissionDesc': 'Past years scores, enrollment statistics',
    'unis.title': 'Choose Your University.',
    'unis.subtitle': 'Information about state universities of Belarus.',
    'unis.inCatalog': 'In catalog',
    'unis.universities': 'universities',
    'unis.totalInRB': 'Total in RB',
    'unis.institutions': 'HE institutions',
    'unis.avgScore': 'Average score',
    'unis.forAdmission': 'for admission',
    'unis.sourceNote': 'Data sources: Average passing scores are for 2025.',
    'applicants.title': 'Choose Your Future Consciously',
    'applicants.subtitle': 'Compare universities, specialties and learn about real employment prospects.',
    'applicants.badge': 'For Applicants',
    'applicants.unis': 'universities',
    'applicants.unisDesc': 'Detailed information about leading universities in Belarus',
    'applicants.jobMarket': 'Job Market',
    'applicants.jobMarketDesc': 'Analysis of vacancies and specialty demand',
    'applicants.demand': 'Market Demand',
    'applicants.demandDesc': 'Analysis of specialty demand',
    'applicants.comparison': 'Specialty Comparison',
    'applicants.comparisonSubtitle': 'Specialty demand and career growth by direction',
    'applicants.dataWarning': 'About the data',
    'applicants.dataWarningDesc': 'Salary data is based on vacancies from rabota.by.',
    'students.title': 'Prepare for the Job Market',
    'students.subtitle': 'Find out which skills are in demand, how much employers pay.',
    'students.badge': 'For Students',
    'students.jobMarket': 'Job Market',
    'students.jobMarketDesc': 'Current vacancy and salary statistics',
    'students.criteria': 'Important Criteria',
    'students.criteriaDesc': 'ML analysis of successful employment factors',
    'students.growth': 'Career Growth',
    'students.growthDesc': 'Career paths in different professions',
    'market.title': 'Job Market',
    'market.titleValue': 'Know Your Worth.',
    'market.vacancies': 'vacancies',
    'market.avgSalary': 'Average salary',
    'market.loading': 'Loading...',
    'market.dataFrom': 'Data loaded from rabota.by',
    'market.demand': 'Demand',
    'market.high': 'high',
    'market.medium': 'medium',
    'market.low': 'low',
    'market.trend': 'Trend',
    'market.up': 'growing',
    'market.down': 'declining',
    'market.stable': 'stable',
    'market.experience': 'Required experience',
    'market.noExperience': 'No experience',
    'market.years': 'years',
    'market.analysis': 'Analysis of {count} vacancies from rabota.by.',
    'market.updated': 'Updated',
    'category.it': 'IT',
    'category.medicine': 'Medicine',
    'category.engineering': 'Engineering',
    'category.economics': 'Economics',
    'category.education': 'Education',
    'category.law': 'Law',
    'category.marketing': 'Marketing',
    'category.design': 'Design',
    'category.media': 'Media',
    'category.sales': 'Sales',
    'category.admin': 'Administrative work',
    'category.construction': 'Construction',
    'category.transport': 'Transport',
    'category.production': 'Production',
    'category.agriculture': 'Agriculture',
    'category.other': 'Other',
    'professions.title': 'In-Demand Professions',
    'professions.subtitle': 'Top specialties by number of vacancies',
    'professions.filter': 'Filter',
    'professions.all': 'All',
    'professions.highDemand': 'High demand',
    'professions.mediumDemand': 'Medium demand',
    'professions.lowDemand': 'Low demand',
    'professions.category': 'Category',
    'professions.workers': 'Workers',
    'professions.employees': 'Employees',
    'professions.specialists': 'Specialists',
    'professions.loadError': 'Failed to load profession data.',
    'analysis.title': 'ML Analysis',
    'analysis.subtitle': 'Employment prediction based on machine learning',
    'analysis.model': 'Model',
    'analysis.modelDesc': 'Combination of XGBoost, LightGBM and RandomForest',
    'analysis.shap': 'SHAP Analysis',
    'analysis.shapDesc': 'Model interpretability',
    'analysis.features': '12 features',
    'analysis.featuresDesc': 'GPA, experience, university, city, internships, projects',
    'analysis.accuracy': 'Accuracy',
    'analysis.rocAuc': 'ROC-AUC',
    'analysis.selectFaculty': 'Select direction',
    'analysis.selectUniversity': 'Select university',
    'analysis.predict': 'Predict Chances',
    'analysis.employed': 'Employment probability',
    'analysis.accuracyVal': 'Accuracy',
    'analysis.accuracyDesc': 'Proportion of correct predictions',
    'analysis.precisionVal': 'Precision',
    'analysis.precisionDesc': 'Positive predictive value',
    'analysis.recallVal': 'Recall',
    'analysis.recallDesc': 'True positive rate',
    'analysis.facultyEmploymentRate': 'Direction',
    'analysis.gpaNormalized': 'GPA',
    'analysis.experienceNormalized': 'Work experience',
    'analysis.cityEconomicFactor': 'City',
    'analysis.universityPrestige': 'University prestige',
    'analysis.industryGrowthRate': 'Industry growth',
    'analysis.compositeMarketScore': 'Market potential',
    'analysis.facultyUniversityMatch': 'University-faculty match',
    'analysis.internshipsNormalized': 'Internships',
    'analysis.projectsNormalized': 'Projects',
    'analysis.isotonicCalibration': 'Isotonic calibration',
    'analysis.isotonicCalibrationDesc': 'Probability adjustment for more accurate predictions',
    'stats.title': 'Labor Market Data',
    'stats.subtitle': 'Complete analytics of vacancies, salaries and predictions.',
    'stats.vacancies': 'Vacancies',
    'stats.salaries': 'Salaries',
    'stats.mlAnalysis': 'ML Analysis',
    'stats.methodology': 'Methodology',
    'stats.vacanciesAnalytics': 'Labor Market Analytics',
    'stats.vacanciesAnalyticsDesc': 'Data from rabota.by',
    'stats.totalVacancies': 'Total vacancies',
    'stats.byCategories': 'by {count} categories',
    'stats.topDirection': 'Top direction',
    'stats.noData': 'No data',
    'stats.noSearchResults': 'No vacancies matching search',
    'stats.vacanciesCount': 'vacancies',
    'stats.avgSalary': 'Average salary',
    'stats.categories': 'Categories',
    'stats.directions': 'directions',
    'stats.detailedStats': 'Detailed statistics by direction',
    'stats.category': 'Category',
    'stats.vacanciesShort': 'Vacancies',
    'stats.avgSalaryShort': 'Avg salary',
    'stats.range': 'Range',
    'stats.allVacancies': 'All vacancies',
    'stats.vacancy': 'Vacancy',
    'stats.company': 'Company',
    'stats.city': 'City',
    'stats.salary': 'Salary',
    'stats.source': 'Source',
    // Salary Statistics
    'salary.title': 'Salary Statistics',
    'salary.avgByCategory': 'Average salary by category',
    'auth.login': 'Sign In',
    'auth.register': 'Register',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.viewAll': 'View All',
    'common.seeMore': 'See More',
    'common.back': 'Back',
    'common.year': 'Year',
    'common.city': 'City',
    'common.noData': 'N/A',
    'uni.notFound': 'University not found',
    'uni.notFoundDesc': 'Unfortunately, information about this university is not available.',
    'uni.backToList': 'Back to list',
    'uni.about': 'About university',
    'uni.website': 'Website',
    'uni.scores': 'Scores',
    'uni.faculties': 'faculties',
    'uni.institutes': 'institutes',
    'uni.specialties': 'specialties',
    'uni.passingScores': 'Passing Scores',
    'uni.passingScoresYears': '(2022-2025)',
    'uni.minScore': 'Min. score',
    'uni.avgScore': 'Avg. score',
    'uni.budget': 'Budget',
    'uni.paid': 'Paid',
    'uni.places': 'Places',
    'uni.faculty': 'Faculty',
    'uni.allFaculties': 'All faculties and institutes',
    'uni.allSpecialties': 'All specialties',
    'uni.noData': 'No data',
    'chat.placeholder': 'Write: "320 points, I want IT in Minsk"...',
    'chat.suggestions': 'Popular questions',
    'admission.title': 'Admission Statistics',
    'admission.subtitle': 'Historical data on passing scores and number of places',
    'admission.allYears': 'All years',
    'admission.allUniversities': 'All universities',
    'admission.allFaculties': 'All faculties',
    'admission.university': 'University',
    'admission.faculty': 'Faculty',
    'admission.activeFilters': 'Active filters',
    'admission.budgetPlaces': 'Budget places',
    'admission.paidPlaces': 'Paid places',
    'admission.avgScore': 'Average score',
    'admission.competition': 'Competition (pers/place)',
    'admission.table': 'Table',
    'admission.charts': 'Charts',
    'admission.comparison': 'Year comparison',
    'admission.detailStats': 'Detailed statistics by specialty',
    'admission.detailStatsDesc': 'Data on passing scores and number of places',
    'admission.specialty': 'Specialty',
    'admission.uni': 'University',
    'admission.year': 'Year',
    'admission.budget': 'Budget',
    'admission.paid': 'Paid',
    'admission.minScore': 'Min. score',
    'admission.avgScoreShort': 'Avg. score',
    'admission.applications': 'Applications',
    'admission.noData': 'No data to display.',
    'admission.noDataDesc': 'Data is loaded from the database. Make sure the admission_stats table is populated.',
    'admission.placesDynamics': 'Number of places dynamics',
    'admission.placesDynamicsDesc': 'Budget and paid places by years',
    'admission.scoreDynamics': 'Passing scores dynamics',
    'admission.scoreDynamicsDesc': 'Average passing score by years',
    'admission.minScores': 'Minimum passing scores',
    'admission.minScoresDesc': 'Minimum score dynamics by years',
    'admission.noChartData': 'No data for chart',
    'admission.comparisonTitle': 'Passing scores comparison by years',
    'admission.comparisonDesc': 'Select a specialty for detailed comparison of indicators over different years',
    'admission.comparisonNeedData': 'Multiple years of data needed for comparison',
    'admission.selectAllYears': 'Select "All years" in the filter to view comparison',
    'admission.budgetShort': 'Budget',
    'admission.applicationsShort': 'Applications',
    'admission.dataSource': 'Data source:',
    'admission.dataSourceDesc': 'Statistics is loaded from the database. Use parsing in admin panel or add data manually. Only real data from admission_stats table is displayed.',
    'admission.yearBadge': 'year',
  },
  be: {
    'profile.title': 'Профіль',
    'profile.back': 'Назад',
    'profile.email': 'Email',
    'profile.role': 'Роля',
    'profile.admin': 'Адміністратар',
    'profile.user': 'Карыстальнік',
    'profile.appearance': 'Знешні выгляд',
    'profile.appearanceDesc': 'Выберыце тэму афармлення',
    'profile.theme.light': 'Светлая',
    'profile.theme.dark': 'Цёмная',
    'profile.theme.highContrast': 'Для слабабачных',
    'profile.language': 'Мова інтэрфейсу',
    'profile.languageDesc': 'Выберыце мову інтэрфейсу',
    'profile.actions': 'Дзеянні',
    'profile.adminPanel': 'Перайсці ѡ адмін-панэль',
    'profile.changePassword': 'Змяніць пароль',
    'profile.logout': 'Выйсці з акаунта',
    'profile.logoutSuccess': 'Выход выкананы',
    'profile.logoutSuccessDesc': 'Вы паспяхова выйшлі з акаунта.',
    'profile.loading': 'Загрузка...',
    'nav.home': 'Галоўная',
    'nav.applicants': 'Для абітурыентаў',
    'nav.students': 'Для студэнтаў',
    'nav.analytics': 'Аналітыка',
    'nav.admission': 'Паступленне',
    'hero.title': 'Усё пра вышэйшую асвету',
    'hero.subtitle': 'Даведнік для абітурыентаў і студэнтаў',
    'hero.chooseUni': 'Выбраць ВНУ',
    'hero.forApplicants': 'Для абітурыентаў',
    'hero.analytics': 'Аналітыка',
    'hero.register': 'Рэгістрацыя',
    'hero.welcome': 'Вітаем,',
    'hero.continue': 'Працягніце пошук або праверце абраныя універсітэты',
    'hero.search': 'Пошук універсітэта або спецыяльнасці...',
    'hero.noResults': 'Універсітэты не знойдзены',
    'hero.unis': 'ВНУ',
    'hero.vacancies': 'Вакансій у базе',
    'hero.sources': 'Крыніцы дадзеных',
    'hero.dataNotice': 'Дадзеныя атрыманы з адкрытых крыніц',
    'footer.statistics': 'Статыстыка',
    'footer.universities': 'Універсітэты',
    'footer.jobMarket': 'Рынак працы',
    'footer.mlAnalysis': 'ML аналіз',
    'footer.dataNote': 'Дадзеныя на аснове анализу rabota.by',
    'quickLinks.title': 'Выберыце свой шлях',
    'quickLinks.subtitle': 'Дадзеныя і інструменты для рашэнняў',
    'quickLinks.forApplicants': 'Для абітурыентаў',
    'quickLinks.forApplicantsDesc': 'Праходныя балы, спецыяльнасці, тэрміны',
    'quickLinks.forStudents': 'Для студэнтаў',
    'quickLinks.forStudentsDesc': 'Рынак працы, зарплаты, вопыт',
    'quickLinks.statistics': 'Статыстыка',
    'quickLinks.statisticsDesc': 'Вакансіі, зарплаты, ML-анализ',
    'quickLinks.admission': 'Паступленне',
    'quickLinks.admissionDesc': 'Балы мінулых гадоў',
    'unis.title': 'Выберыце свой універсітэт.',
    'unis.subtitle': 'Інфармацыя аб дзяржаўных універсітэтах Беларусі.',
    'unis.inCatalog': 'У каталозе',
    'unis.universities': 'універсітэтаў',
    'unis.totalInRB': 'Усяго ѡ РБ',
    'unis.institutions': 'устаноў ВА',
    'unis.avgScore': 'Сярэдні бал',
    'unis.forAdmission': 'для паступлення',
    'unis.sourceNote': 'Крыніцы дадзеных: Сярэднія праходныя балы.',
    'applicants.title': 'Выберыце сваё будучыню свядома',
    'applicants.subtitle': 'Параўнайце універсітэты і спецыяльнасці.',
    'applicants.badge': 'Для абітурыентаў',
    'applicants.unis': 'універсітэтаў',
    'applicants.unisDesc': 'Інфармацыя аб вядучых ВНУ Беларусі',
    'applicants.jobMarket': 'Рынак працы',
    'applicants.jobMarketDesc': 'Аналіз вакансій і попыту',
    'applicants.demand': 'Попыт на рынку',
    'applicants.demandDesc': 'Аналіз попыту спецыяльнасцяў',
    'applicants.comparison': 'Параўнанне спецыяльнасцяў',
    'applicants.comparisonSubtitle': 'Попыт і карьерны рост',
    'applicants.dataWarning': 'Пра дадзеныя',
    'applicants.dataWarningDesc': 'Дадзеныя аб зарплатах з rabota.by.',
    'students.title': 'Падрыхтуйцеся да рынка працы',
    'students.subtitle': 'Даведайцеся, якія навыкі ѡ запаце.',
    'students.badge': 'Для студэнтаў',
    'students.jobMarket': 'Рынак працы',
    'students.jobMarketDesc': 'Статыстыка вакансій і зарплат',
    'students.criteria': 'Важныя крытэры',
    'students.criteriaDesc': 'ML-анализ фактараў працаўладкавання',
    'students.growth': 'Карьерны рост',
    'students.growthDesc': 'Шляхі развіцця',
    'market.title': 'Рынак працы',
    'market.titleValue': 'Ведайце сваю каштоўнасць.',
    'market.vacancies': 'вакансій',
    'market.avgSalary': 'Сярэдняя зарплата',
    'market.loading': 'Загрузка...',
    'market.dataFrom': 'Дадзеныя з rabota.by',
    'market.demand': 'Попыт',
    'market.high': 'высокі',
    'market.medium': 'сярэдні',
    'market.low': 'нізкі',
    'market.trend': 'Трэнд',
    'market.up': 'расце',
    'market.down': 'падае',
    'market.stable': 'стабільна',
    'market.experience': 'Патрабаваны вопыт',
    'market.noExperience': 'Без вопыту',
    'market.years': 'гадоў',
    'market.analysis': 'Аналіз {count} вакансій з rabota.by.',
    'market.updated': 'Абноўлена',
    'category.it': 'IT',
    'category.medicine': 'Медыцына',
    'category.engineering': 'Інжынерыя',
    'category.economics': 'Эканоміка',
    'category.education': 'Педагогіка',
    'category.law': 'Юрыспрудэнцыя',
    'category.marketing': 'Маркетынг',
    'category.design': 'Дызайн',
    'category.media': 'Медыа',
    'category.sales': 'Продажы',
    'category.admin': 'Адміністрацыйная работа',
    'category.construction': 'Будаўніцтва',
    'category.transport': 'Транспарт',
    'category.production': 'Вытворчасць',
    'category.agriculture': 'Сельская гаспадарка',
    'category.other': 'Іншае',
    'professions.title': 'Папулярныя прафесіі',
    'professions.subtitle': 'Топ спецыяльнасцяў па вакансіях',
    'professions.filter': 'Фільтр',
    'professions.all': 'Усе',
    'professions.highDemand': 'Высокі попыт',
    'professions.mediumDemand': 'Сярэдні попыт',
    'professions.lowDemand': 'Нізкі попыт',
    'professions.category': 'Катэгорыя',
    'professions.workers': 'Работнікі',
    'professions.employees': 'Служачыя',
    'professions.specialists': 'Спецыялісты',
    'professions.loadError': 'Не атрымалася загрузіць дадзеныя.',
    'analysis.title': 'ML-анализ',
    'analysis.subtitle': 'Прагноз працаўладкавання',
    'analysis.model': 'Мадэль',
    'analysis.modelDesc': 'Камбінацыя XGBoost, LightGBM',
    'analysis.shap': 'SHAP-анализ',
    'analysis.shapDesc': 'Інтэрпрэтаванасць мадэлі',
    'analysis.features': '12 прыкмет',
    'analysis.featuresDesc': 'GPA, вопыт, ВНУ, горад',
    'analysis.accuracy': 'Дакладнасць',
    'analysis.rocAuc': 'ROC-AUC',
    'analysis.selectFaculty': 'Выберыце напрамак',
    'analysis.selectUniversity': 'Выберыце універсітэт',
    'analysis.predict': 'Прагназаваць шансы',
    'analysis.employed': 'Верагоднасць працаўладкавання',
    'analysis.accuracyVal': 'Дакладнасць',
    'analysis.accuracyDesc': 'Доля правільных прагнозаў',
    'analysis.precisionVal': 'Precision',
    'analysis.precisionDesc': 'Дакладнасць станоўчых прагнозаў',
    'analysis.recallVal': 'Recall',
    'analysis.recallDesc': 'Поўнасць выяўлення',
    'analysis.facultyEmploymentRate': 'Напрамак',
    'analysis.gpaNormalized': 'Сярэдні бал',
    'analysis.experienceNormalized': 'Вопыт работы',
    'analysis.cityEconomicFactor': 'Горад',
    'analysis.universityPrestige': 'Прэстыж ВНУ',
    'analysis.industryGrowthRate': 'Рост індустрыі',
    'analysis.compositeMarketScore': 'Рыначны патэнцыял',
    'analysis.facultyUniversityMatch': 'Сумяшчальнасць ВНУ-факультэт',
    'analysis.internshipsNormalized': 'Стажыроўкі',
    'analysis.projectsNormalized': 'Праекты',
    'analysis.isotonicCalibration': 'Ізатанічная каліброўка',
    'analysis.isotonicCalibrationDesc': 'Карэкціроўка верагоднасцей для больш дакладных прагнозаў',
    'stats.title': 'Дадзеныя пра рынак працы',
    'stats.subtitle': 'Поўная аналітыка вакансій і зарплат.',
    'stats.vacancies': 'Вакансіі',
    'stats.salaries': 'Зарплаты',
    'stats.mlAnalysis': 'ML-анализ',
    'stats.methodology': 'Метадалогія',
    'stats.vacanciesAnalytics': 'Аналітыка рынка працы',
    'stats.vacanciesAnalyticsDesc': 'Дадзеныя з rabota.by',
    'stats.totalVacancies': 'Усяго вакансій',
    'stats.byCategories': 'па {count} катэгорыям',
    'stats.topDirection': 'Топ напрамак',
    'stats.noData': 'Няма дадзеных',
    'stats.noSearchResults': 'Няма вакансій адпаведных пошуку',
    'stats.vacanciesCount': 'вакансій',
    'stats.avgSalary': 'Сярэдняя зарплата',
    'stats.categories': 'Катэгорый',
    'stats.directions': 'напрамкаў',
    'stats.detailedStats': 'Дэтальная статыстыка па напрамкам',
    'stats.category': 'Катэгорыя',
    'stats.vacanciesShort': 'Вакансій',
    'stats.avgSalaryShort': 'Сяр. зарплата',
    'stats.range': 'Дыяпазон',
    'stats.allVacancies': 'Усе вакансіі',
    'stats.vacancy': 'Вакансія',
    'stats.company': 'Кампанія',
    'stats.city': 'Горад',
    'stats.salary': 'Зарплата',
    'stats.source': 'Крыніца',
    // Salary Statistics
    'salary.title': 'Статыстыка зарплат',
    'salary.avgByCategory': 'Сярэдняя зарпалата па катэгорыям',
    'auth.login': 'Увайсці',
    'auth.register': 'Рэгістрацыя',
    'common.loading': 'Загрузка...',
    'common.error': 'Памылка',
    'common.save': 'Захаваць',
    'common.cancel': 'Адмена',
    'common.close': 'Закрыць',
    'common.search': 'Пошук',
    'common.filter': 'Фільтр',
    'common.viewAll': 'Паглядзець усё',
    'common.seeMore': 'Падрабязней',
    'common.back': 'Назад',
    'common.year': 'Год',
    'common.city': 'Горад',
    'common.noData': 'Н/Д',
    'uni.notFound': 'Універсітэт не знойдзен',
    'uni.notFoundDesc': 'Нажаль, інфармацыя адсутнічае.',
    'uni.backToList': 'Вярнуцца да спісу',
    'uni.about': 'Пра універсітэт',
    'uni.website': 'Сайт',
    'uni.scores': 'Балы',
    'uni.faculties': 'факультэтаў',
    'uni.institutes': 'інстытутаў',
    'uni.specialties': 'спецыяльнасцяў',
    'uni.passingScores': 'Праходныя балы',
    'uni.passingScoresYears': '(2022-2025)',
    'uni.minScore': 'Мін. бал',
    'uni.avgScore': 'Сяр. бал',
    'uni.budget': 'Бюджэт',
    'uni.paid': 'Платнае',
    'uni.places': 'Месцаў',
    'uni.faculty': 'Факультэт',
    'uni.allFaculties': 'Усе факультэты і інстытуты',
    'uni.allSpecialties': 'Усе спецыяльнасці',
    'uni.noData': 'Няма дадзеных',
    'chat.placeholder': 'Напішыце: "320 балаў, хочу на IT"...',
    'chat.suggestions': 'Папулярныя пытанні',
    'admission.title': 'Статыстыка паступлення',
    'admission.subtitle': 'Гісторычныя дадзеныя аб праходных балах',
    'admission.allYears': 'Усе гады',
    'admission.allUniversities': 'Усе універсітэты',
    'admission.allFaculties': 'Усе факультэты',
    'admission.university': 'Універсітэт',
    'admission.faculty': 'Факультэт',
    'admission.activeFilters': 'Актыўныя фільтры',
    'admission.budgetPlaces': 'Бюджэтных месцаў',
    'admission.paidPlaces': 'Платных месцаў',
    'admission.avgScore': 'Сярэдні бал',
    'admission.competition': 'Конкурс (чал/место)',
    'admission.table': 'Табліца',
    'admission.charts': 'Графікі',
    'admission.comparison': 'Параўнанне па гадах',
    'admission.detailStats': 'Дэтальная статыстыка па спецыяльнасцях',
    'admission.detailStatsDesc': 'Дадзеныя аб праходных балах і колькасці месцаў',
    'admission.specialty': 'Спецыяльнасць',
    'admission.uni': 'Універсітэт',
    'admission.year': 'Год',
    'admission.budget': 'Бюджэт',
    'admission.paid': 'Платное',
    'admission.minScore': 'Мін. бал',
    'admission.avgScoreShort': 'Сяр. бал',
    'admission.applications': 'Заявак',
    'admission.noData': 'Няма дадзеных для адлюстравання.',
    'admission.noDataDesc': 'Дадзеныя загружаюцца з базы. Праверце, што табліца admission_stats запоўнена.',
    'admission.placesDynamics': 'Дынаміка колькасці месцаў',
    'admission.placesDynamicsDesc': 'Бюджэтныя і платныя месцы па гадах',
    'admission.scoreDynamics': 'Дынаміка праходных балаў',
    'admission.scoreDynamicsDesc': 'Сярэдні праходны бал па гадах',
    'admission.minScores': 'Мінімальныя праходныя балы',
    'admission.minScoresDesc': 'Дынаміка мінімальных балаў па гадах',
    'admission.noChartData': 'Няма дадзеных для графіка',
    'admission.comparisonTitle': 'Параўнанне праходных балаў па гадах',
    'admission.comparisonDesc': 'Выберыце спецыяльнасць для дэтальнага параўнання паказчыкаў за розныя гады',
    'admission.comparisonNeedData': 'Для параўнення патрэбны дадзеныя за некалькі гадоў',
    'admission.selectAllYears': 'Выберыце "Усе гады" у фільтры для прагляду параўнання',
    'admission.budgetShort': 'Бюджэт',
    'admission.applicationsShort': 'Заяўкі',
    'admission.dataSource': 'Крыніца дадзеных:',
    'admission.dataSourceDesc': 'Статыстыка загружаецца з базы дадзеных. Для абнаўлення выкарыстоўвайце парсінг у панэлі адміністратара або дадайце дадзеныя ўручную. Адлюстроўваюцца толькі рэальныя дадзеныя з табліцы admission_stats.',
    'admission.yearBadge': 'год',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
      if (stored && ['ru', 'en', 'be'].includes(stored)) {
        return stored;
      }
    }
    return 'ru';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['ru'][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

interface UniversityNameFields {
  short_name?: string | null;
  short_name_en?: string | null;
  short_name_be?: string | null;
  full_name?: string | null;
  full_name_en?: string | null;
  full_name_be?: string | null;
}

interface FacultyNameFields {
  name?: string | null;
  name_en?: string | null;
  name_be?: string | null;
}

export function getUniversityTranslatedName(uni: UniversityNameFields, language: Language): string {
  if (language === 'en' && uni.short_name_en) return uni.short_name_en;
  if (language === 'be' && uni.short_name_be) return uni.short_name_be;
  return uni.short_name || uni.full_name || '';
}

export function getFacultyTranslatedName(fac: FacultyNameFields, language: Language): string {
  if (language === 'en' && fac.name_en) return fac.name_en;
  if (language === 'be' && fac.name_be) return fac.name_be;
  return fac.name || '';
}

export function translateCategory(category: string, language: Language): string {
  const key = `category.${category.toLowerCase().replace(/[^a-z]/g, '')}`;
  const translations: Record<Language, Record<string, string>> = {
    ru: {
      it: 'ИТ',
      medicine: 'Медицина',
      engineering: 'Инженерия',
      economics: 'Экономика',
      education: 'Педагогика',
      law: 'Юриспруденция',
      marketing: 'Маркетинг',
      design: 'Дизайн',
      media: 'Медиа',
      sales: 'Продажи',
      admin: 'Административная работа',
      construction: 'Строительство',
      transport: 'Транспорт',
      production: 'Производство',
      agriculture: 'Сельское хозяйство',
      other: 'Другое',
    },
    en: {
      it: 'IT',
      medicine: 'Medicine',
      engineering: 'Engineering',
      economics: 'Economics',
      education: 'Education',
      law: 'Law',
      marketing: 'Marketing',
      design: 'Design',
      media: 'Media',
      sales: 'Sales',
      admin: 'Administrative',
      construction: 'Construction',
      transport: 'Transport',
      production: 'Production',
      agriculture: 'Agriculture',
      other: 'Other',
    },
    be: {
      it: 'IT',
      medicine: 'Медыцына',
      engineering: 'Інжынерыя',
      economics: 'Эканоміка',
      education: 'Педагогіка',
      law: 'Юрыспрудэнцыя',
      marketing: 'Маркетынг',
      design: 'Дызайн',
      media: 'Медыа',
      sales: 'Продажы',
      admin: 'Адміністрацыйная',
      construction: 'Будаўніцтва',
      transport: 'Транспарт',
      production: 'Вытворчасць',
      agriculture: 'Сельская гаспадарка',
      other: 'Іншае',
    },
  };
  
  const normalizedKey = category.toLowerCase().replace(/[^a-z]/g, '');
  return translations[language][normalizedKey] || category;
}
